// Comprehensive food database with accurate nutritional data
// All values are per 100g unless specified otherwise
// Sources: USDA FoodData Central, verified nutritional databases

export const comprehensiveFoods = [
  // ============= PROTEINS - MEATS =============

  // Beef
  {
    name: "Ground Beef 70/30 (raw)",
    brand: "",
    calories: 332,
    protein: 14,
    carbs: 0,
    fat: 30,
    fiber: 0,
    sugar: 0,
    sodium: 0.067,
    saturated_fat: 11.7,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ground Beef 80/20 (raw)",
    brand: "",
    calories: 254,
    protein: 17.2,
    carbs: 0,
    fat: 20,
    fiber: 0,
    sugar: 0,
    sodium: 0.066,
    saturated_fat: 7.8,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ground Beef 90/10 (raw)",
    brand: "",
    calories: 176,
    protein: 20,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sugar: 0,
    sodium: 0.066,
    saturated_fat: 3.9,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ground Beef 93/7 (raw)",
    brand: "",
    calories: 152,
    protein: 21.4,
    carbs: 0,
    fat: 7,
    fiber: 0,
    sugar: 0,
    sodium: 0.066,
    saturated_fat: 2.8,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ribeye Steak (raw)",
    brand: "",
    calories: 265,
    protein: 21,
    carbs: 0,
    fat: 20,
    fiber: 0,
    sugar: 0,
    sodium: 0.054,
    saturated_fat: 8.5,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Sirloin Steak (raw)",
    brand: "",
    calories: 183,
    protein: 23,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sugar: 0,
    sodium: 0.056,
    saturated_fat: 3.8,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Filet Mignon (raw)",
    brand: "",
    calories: 218,
    protein: 22,
    carbs: 0,
    fat: 14,
    fiber: 0,
    sugar: 0,
    sodium: 0.045,
    saturated_fat: 5.4,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "T-Bone Steak (raw)",
    brand: "",
    calories: 247,
    protein: 19,
    carbs: 0,
    fat: 19,
    fiber: 0,
    sugar: 0,
    sodium: 0.058,
    saturated_fat: 7.6,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },

  // Chicken
  {
    name: "Chicken Breast (boneless, skinless, raw)",
    brand: "",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 0.074,
    saturated_fat: 1,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Chicken Thigh (boneless, skinless, raw)",
    brand: "",
    calories: 209,
    protein: 20,
    carbs: 0,
    fat: 14,
    fiber: 0,
    sugar: 0,
    sodium: 0.084,
    saturated_fat: 3.7,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Chicken Wings (raw)",
    brand: "",
    calories: 191,
    protein: 18,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 0.082,
    saturated_fat: 3.5,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Chicken Drumsticks (raw)",
    brand: "",
    calories: 172,
    protein: 18.6,
    carbs: 0,
    fat: 10.5,
    fiber: 0,
    sugar: 0,
    sodium: 0.090,
    saturated_fat: 2.7,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ground Chicken (raw)",
    brand: "",
    calories: 143,
    protein: 17.4,
    carbs: 0,
    fat: 8.1,
    fiber: 0,
    sugar: 0,
    sodium: 0.060,
    saturated_fat: 2.3,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Rotisserie Chicken (meat only)",
    brand: "",
    calories: 184,
    protein: 28.9,
    carbs: 0,
    fat: 7.4,
    fiber: 0,
    sugar: 0,
    sodium: 0.318,
    saturated_fat: 2.1,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },

  // McDonald's Chicken (FIXED - with actual calories)
  {
    name: "McDonald's Chicken McNuggets (6 piece)",
    brand: "McDonald's",
    calories: 270,
    protein: 13,
    carbs: 17,
    fat: 17,
    fiber: 1,
    sugar: 0,
    sodium: 0.500,
    saturated_fat: 3,
    serving_size: "103g",
    category: "Fast Food",
    source: "verified"
  },
  {
    name: "McDonald's McChicken Sandwich",
    brand: "McDonald's",
    calories: 400,
    protein: 14,
    carbs: 39,
    fat: 21,
    fiber: 2,
    sugar: 5,
    sodium: 0.650,
    saturated_fat: 3.5,
    serving_size: "143g",
    category: "Fast Food",
    source: "verified"
  },
  {
    name: "McDonald's Grilled Chicken Sandwich",
    brand: "McDonald's",
    calories: 380,
    protein: 37,
    carbs: 44,
    fat: 7,
    fiber: 3,
    sugar: 11,
    sodium: 1.030,
    saturated_fat: 2,
    serving_size: "199g",
    category: "Fast Food",
    source: "verified"
  },

  // Pork
  {
    name: "Pork Chops (center cut, raw)",
    brand: "",
    calories: 242,
    protein: 19.6,
    carbs: 0,
    fat: 18,
    fiber: 0,
    sugar: 0,
    sodium: 0.055,
    saturated_fat: 6.2,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Pork Tenderloin (raw)",
    brand: "",
    calories: 143,
    protein: 20.9,
    carbs: 0,
    fat: 6.2,
    fiber: 0,
    sugar: 0,
    sodium: 0.053,
    saturated_fat: 2.2,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ground Pork (raw)",
    brand: "",
    calories: 263,
    protein: 16.9,
    carbs: 0,
    fat: 21.2,
    fiber: 0,
    sugar: 0,
    sodium: 0.059,
    saturated_fat: 7.7,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Bacon (raw)",
    brand: "",
    calories: 417,
    protein: 13,
    carbs: 1.3,
    fat: 40,
    fiber: 0,
    sugar: 0,
    sodium: 0.680,
    saturated_fat: 13.7,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ham (sliced, deli)",
    brand: "",
    calories: 145,
    protein: 21,
    carbs: 2,
    fat: 6,
    fiber: 0,
    sugar: 1.5,
    sodium: 1.200,
    saturated_fat: 2,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },

  // Turkey
  {
    name: "Turkey Breast (raw)",
    brand: "",
    calories: 104,
    protein: 24,
    carbs: 0,
    fat: 0.5,
    fiber: 0,
    sugar: 0,
    sodium: 0.065,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ground Turkey 93/7 (raw)",
    brand: "",
    calories: 150,
    protein: 22,
    carbs: 0,
    fat: 7,
    fiber: 0,
    sugar: 0,
    sodium: 0.090,
    saturated_fat: 1.9,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },
  {
    name: "Ground Turkey 85/15 (raw)",
    brand: "",
    calories: 219,
    protein: 20,
    carbs: 0,
    fat: 15,
    fiber: 0,
    sugar: 0,
    sodium: 0.090,
    saturated_fat: 3.9,
    serving_size: "100g",
    category: "Proteins",
    source: "verified"
  },

  // Fish & Seafood
  {
    name: "Salmon (Atlantic, raw)",
    brand: "",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13.4,
    fiber: 0,
    sugar: 0,
    sodium: 0.059,
    saturated_fat: 3.1,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Tuna (Yellowfin, raw)",
    brand: "",
    calories: 109,
    protein: 24.4,
    carbs: 0,
    fat: 0.5,
    fiber: 0,
    sugar: 0,
    sodium: 0.045,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Cod (Pacific, raw)",
    brand: "",
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    sugar: 0,
    sodium: 0.054,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Tilapia (raw)",
    brand: "",
    calories: 96,
    protein: 20,
    carbs: 0,
    fat: 1.7,
    fiber: 0,
    sugar: 0,
    sodium: 0.052,
    saturated_fat: 0.6,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Shrimp (raw)",
    brand: "",
    calories: 85,
    protein: 20,
    carbs: 0,
    fat: 0.5,
    fiber: 0,
    sugar: 0,
    sodium: 0.119,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Canned Tuna in Water",
    brand: "",
    calories: 116,
    protein: 25.5,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    sugar: 0,
    sodium: 0.247,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Canned Salmon",
    brand: "",
    calories: 136,
    protein: 19.8,
    carbs: 0,
    fat: 6,
    fiber: 0,
    sugar: 0,
    sodium: 0.336,
    saturated_fat: 1.4,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Lobster (raw)",
    brand: "",
    calories: 89,
    protein: 19,
    carbs: 0,
    fat: 0.9,
    fiber: 0,
    sugar: 0,
    sodium: 0.296,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },
  {
    name: "Crab (raw)",
    brand: "",
    calories: 83,
    protein: 18,
    carbs: 0.04,
    fat: 0.6,
    fiber: 0,
    sugar: 0,
    sodium: 0.395,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Seafood",
    source: "verified"
  },

  // ============= EGGS & DAIRY =============

  // Eggs
  {
    name: "Eggs (whole, large)",
    brand: "",
    calories: 143,
    protein: 12.6,
    carbs: 0.7,
    fat: 9.5,
    fiber: 0,
    sugar: 0.4,
    sodium: 0.142,
    saturated_fat: 3.1,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Egg Whites",
    brand: "",
    calories: 52,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0,
    sugar: 0.7,
    sodium: 0.166,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Egg Yolks",
    brand: "",
    calories: 322,
    protein: 15.9,
    carbs: 3.6,
    fat: 26.5,
    fiber: 0,
    sugar: 0.6,
    sodium: 0.048,
    saturated_fat: 9.6,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Hard-Boiled Eggs",
    brand: "",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 10.6,
    fiber: 0,
    sugar: 1.1,
    sodium: 0.124,
    saturated_fat: 3.3,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },

  // Milk
  {
    name: "Whole Milk (3.25% fat)",
    brand: "",
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 5.1,
    sodium: 0.043,
    saturated_fat: 1.9,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "2% Milk",
    brand: "",
    calories: 50,
    protein: 3.3,
    carbs: 4.8,
    fat: 2,
    fiber: 0,
    sugar: 5.1,
    sodium: 0.047,
    saturated_fat: 1.3,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "1% Milk",
    brand: "",
    calories: 42,
    protein: 3.4,
    carbs: 4.9,
    fat: 1,
    fiber: 0,
    sugar: 5.2,
    sodium: 0.044,
    saturated_fat: 0.6,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Skim Milk (Fat Free)",
    brand: "",
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    sugar: 5.1,
    sodium: 0.052,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },

  // Cheese
  {
    name: "Cheddar Cheese",
    brand: "",
    calories: 403,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    sugar: 0.5,
    sodium: 0.621,
    saturated_fat: 21,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Mozzarella Cheese (Part Skim)",
    brand: "",
    calories: 254,
    protein: 24,
    carbs: 2.8,
    fat: 16,
    fiber: 0,
    sugar: 1,
    sodium: 0.619,
    saturated_fat: 10,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Parmesan Cheese",
    brand: "",
    calories: 431,
    protein: 38,
    carbs: 4.1,
    fat: 29,
    fiber: 0,
    sugar: 0.9,
    sodium: 1.529,
    saturated_fat: 17,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Cream Cheese",
    brand: "",
    calories: 342,
    protein: 6,
    carbs: 4.1,
    fat: 34,
    fiber: 0,
    sugar: 3.2,
    sodium: 0.321,
    saturated_fat: 19,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Cottage Cheese (2% fat)",
    brand: "",
    calories: 81,
    protein: 11,
    carbs: 3.4,
    fat: 2.3,
    fiber: 0,
    sugar: 2.7,
    sodium: 0.364,
    saturated_fat: 0.9,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Ricotta Cheese (Part Skim)",
    brand: "",
    calories: 138,
    protein: 11.4,
    carbs: 5.1,
    fat: 7.9,
    fiber: 0,
    sugar: 0.3,
    sodium: 0.125,
    saturated_fat: 4.9,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Swiss Cheese",
    brand: "",
    calories: 380,
    protein: 27,
    carbs: 5.4,
    fat: 28,
    fiber: 0,
    sugar: 1.3,
    sodium: 0.192,
    saturated_fat: 17.8,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Blue Cheese",
    brand: "",
    calories: 353,
    protein: 21,
    carbs: 2.3,
    fat: 29,
    fiber: 0,
    sugar: 0.5,
    sodium: 1.395,
    saturated_fat: 19,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Feta Cheese",
    brand: "",
    calories: 264,
    protein: 14,
    carbs: 4.1,
    fat: 21,
    fiber: 0,
    sugar: 4.1,
    sodium: 1.116,
    saturated_fat: 15,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },

  // Yogurt
  {
    name: "Greek Yogurt (Plain, Non-fat)",
    brand: "",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.2,
    sodium: 0.036,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Greek Yogurt (Plain, Whole Milk)",
    brand: "",
    calories: 97,
    protein: 9,
    carbs: 3.9,
    fat: 5,
    fiber: 0,
    sugar: 3.6,
    sodium: 0.035,
    saturated_fat: 2.5,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },
  {
    name: "Regular Yogurt (Plain, Whole Milk)",
    brand: "",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    sugar: 4.7,
    sodium: 0.046,
    saturated_fat: 2.1,
    serving_size: "100g",
    category: "Eggs & Dairy",
    source: "verified"
  },

  // ============= GRAINS & BREAD =============

  // Rice
  {
    name: "White Rice (cooked)",
    brand: "",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Brown Rice (cooked)",
    brand: "",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 0.005,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Jasmine Rice (cooked)",
    brand: "",
    calories: 148,
    protein: 2.8,
    carbs: 32,
    fat: 0.4,
    fiber: 0.6,
    sugar: 0.1,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Basmati Rice (cooked)",
    brand: "",
    calories: 121,
    protein: 3.5,
    carbs: 25,
    fat: 0.4,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Wild Rice (cooked)",
    brand: "",
    calories: 101,
    protein: 4,
    carbs: 21,
    fat: 0.3,
    fiber: 1.8,
    sugar: 0.7,
    sodium: 0.003,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },

  // Pasta
  {
    name: "Spaghetti (cooked)",
    brand: "",
    calories: 158,
    protein: 5.8,
    carbs: 31,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.6,
    sodium: 0.001,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Penne Pasta (cooked)",
    brand: "",
    calories: 156,
    protein: 5.7,
    carbs: 31,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.8,
    sodium: 0.001,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Whole Wheat Pasta (cooked)",
    brand: "",
    calories: 124,
    protein: 5.3,
    carbs: 27,
    fat: 0.5,
    fiber: 4.5,
    sugar: 0.8,
    sodium: 0.003,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Lasagna Noodles (cooked)",
    brand: "",
    calories: 155,
    protein: 5.7,
    carbs: 30,
    fat: 1.3,
    fiber: 1.4,
    sugar: 1.5,
    sodium: 0.006,
    saturated_fat: 0.3,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },

  // Bread
  {
    name: "White Bread",
    brand: "",
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.7,
    sugar: 5,
    sodium: 0.491,
    saturated_fat: 0.7,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Whole Wheat Bread",
    brand: "",
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 6.8,
    sugar: 6,
    sodium: 0.400,
    saturated_fat: 0.7,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Sourdough Bread",
    brand: "",
    calories: 266,
    protein: 9,
    carbs: 51,
    fat: 2.5,
    fiber: 2.4,
    sugar: 2.8,
    sodium: 0.508,
    saturated_fat: 0.5,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Rye Bread",
    brand: "",
    calories: 259,
    protein: 9,
    carbs: 48,
    fat: 3.3,
    fiber: 5.8,
    sugar: 3.8,
    sodium: 0.603,
    saturated_fat: 0.6,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Bagel (Plain)",
    brand: "",
    calories: 257,
    protein: 10,
    carbs: 50,
    fat: 1.6,
    fiber: 2.3,
    sugar: 7.6,
    sodium: 0.430,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "English Muffin",
    brand: "",
    calories: 223,
    protein: 8.7,
    carbs: 44,
    fat: 1.8,
    fiber: 2.7,
    sugar: 2,
    sodium: 0.394,
    saturated_fat: 0.3,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Pita Bread",
    brand: "",
    calories: 275,
    protein: 9.8,
    carbs: 56,
    fat: 1.2,
    fiber: 2.2,
    sugar: 1.3,
    sodium: 0.536,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Tortilla (Flour)",
    brand: "",
    calories: 304,
    protein: 8.2,
    carbs: 50,
    fat: 7.9,
    fiber: 3.1,
    sugar: 2.2,
    sodium: 0.599,
    saturated_fat: 1.9,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Tortilla (Corn)",
    brand: "",
    calories: 218,
    protein: 5.7,
    carbs: 45,
    fat: 2.9,
    fiber: 6.3,
    sugar: 0.9,
    sodium: 0.020,
    saturated_fat: 0.4,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },

  // Cereals & Oats
  {
    name: "Oatmeal (cooked)",
    brand: "",
    calories: 71,
    protein: 2.5,
    carbs: 12,
    fat: 1.5,
    fiber: 1.7,
    sugar: 0.3,
    sodium: 0.049,
    saturated_fat: 0.3,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Instant Oats (dry)",
    brand: "",
    calories: 379,
    protein: 13.2,
    carbs: 67,
    fat: 6.5,
    fiber: 10,
    sugar: 1.4,
    sodium: 0.220,
    saturated_fat: 1.1,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Steel Cut Oats (cooked)",
    brand: "",
    calories: 71,
    protein: 2.5,
    carbs: 12,
    fat: 1.5,
    fiber: 1.7,
    sugar: 0.3,
    sodium: 0.004,
    saturated_fat: 0.3,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Quinoa (cooked)",
    brand: "",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 0.007,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },
  {
    name: "Couscous (cooked)",
    brand: "",
    calories: 112,
    protein: 3.8,
    carbs: 23,
    fat: 0.2,
    fiber: 1.4,
    sugar: 0.1,
    sodium: 0.005,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Grains",
    source: "verified"
  },

  // ============= VEGETABLES =============

  // Green Vegetables
  {
    name: "Broccoli (raw)",
    brand: "",
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 0.033,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Spinach (raw)",
    brand: "",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 0.079,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Kale (raw)",
    brand: "",
    calories: 49,
    protein: 4.3,
    carbs: 8.8,
    fat: 0.9,
    fiber: 3.6,
    sugar: 2.3,
    sodium: 0.038,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Lettuce (Romaine)",
    brand: "",
    calories: 17,
    protein: 1.2,
    carbs: 3.3,
    fat: 0.3,
    fiber: 2.1,
    sugar: 1.2,
    sodium: 0.008,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Lettuce (Iceberg)",
    brand: "",
    calories: 14,
    protein: 0.9,
    carbs: 3,
    fat: 0.1,
    fiber: 1.2,
    sugar: 2,
    sodium: 0.010,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Asparagus (raw)",
    brand: "",
    calories: 20,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
    sugar: 1.9,
    sodium: 0.002,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Green Beans (raw)",
    brand: "",
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.2,
    fiber: 2.7,
    sugar: 3.3,
    sodium: 0.006,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Brussels Sprouts (raw)",
    brand: "",
    calories: 43,
    protein: 3.4,
    carbs: 8.9,
    fat: 0.3,
    fiber: 3.8,
    sugar: 2.2,
    sodium: 0.025,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Cucumber (with peel)",
    brand: "",
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 0.002,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Celery (raw)",
    brand: "",
    calories: 16,
    protein: 0.7,
    carbs: 3,
    fat: 0.2,
    fiber: 1.6,
    sugar: 1.3,
    sodium: 0.080,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Zucchini (raw)",
    brand: "",
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    sugar: 2.5,
    sodium: 0.008,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },

  // Root Vegetables
  {
    name: "Potato (raw, with skin)",
    brand: "",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.1,
    sugar: 0.8,
    sodium: 0.006,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Sweet Potato (raw)",
    brand: "",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 0.055,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Carrots (raw)",
    brand: "",
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 0.069,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Beets (raw)",
    brand: "",
    calories: 43,
    protein: 1.6,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 6.8,
    sodium: 0.078,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Onion (raw)",
    brand: "",
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    sugar: 4.2,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Garlic (raw)",
    brand: "",
    calories: 149,
    protein: 6.4,
    carbs: 33,
    fat: 0.5,
    fiber: 2.1,
    sugar: 1,
    sodium: 0.017,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },

  // Other Vegetables
  {
    name: "Tomatoes (raw)",
    brand: "",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 0.005,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Bell Pepper (Red, raw)",
    brand: "",
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    sugar: 4.2,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Bell Pepper (Green, raw)",
    brand: "",
    calories: 20,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
    fiber: 1.7,
    sugar: 2.4,
    sodium: 0.003,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Cauliflower (raw)",
    brand: "",
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
    sugar: 1.9,
    sodium: 0.030,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Mushrooms (White, raw)",
    brand: "",
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
    sugar: 2,
    sodium: 0.005,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Corn (Sweet, raw)",
    brand: "",
    calories: 86,
    protein: 3.3,
    carbs: 19,
    fat: 1.3,
    fiber: 2,
    sugar: 6.3,
    sodium: 0.015,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Eggplant (raw)",
    brand: "",
    calories: 25,
    protein: 1,
    carbs: 5.9,
    fat: 0.2,
    fiber: 3,
    sugar: 3.5,
    sodium: 0.002,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },
  {
    name: "Avocado",
    brand: "",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 0.007,
    saturated_fat: 2.1,
    serving_size: "100g",
    category: "Vegetables",
    source: "verified"
  },

  // ============= FRUITS =============

  // Common Fruits
  {
    name: "Apple (with skin)",
    brand: "",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10.4,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Apple (Granny Smith)",
    brand: "",
    calories: 58,
    protein: 0.4,
    carbs: 13.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 9.6,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Apple (Honeycrisp)",
    brand: "",
    calories: 57,
    protein: 0.3,
    carbs: 14.3,
    fat: 0.2,
    fiber: 2.4,
    sugar: 11.3,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Banana",
    brand: "",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Orange",
    brand: "",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9.4,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Grapes (Red or Green)",
    brand: "",
    calories: 67,
    protein: 0.6,
    carbs: 17,
    fat: 0.4,
    fiber: 0.9,
    sugar: 16.3,
    sodium: 0.002,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Strawberries",
    brand: "",
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Blueberries",
    brand: "",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Raspberries",
    brand: "",
    calories: 52,
    protein: 1.2,
    carbs: 12,
    fat: 0.7,
    fiber: 6.5,
    sugar: 4.4,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Blackberries",
    brand: "",
    calories: 43,
    protein: 1.4,
    carbs: 9.6,
    fat: 0.5,
    fiber: 5.3,
    sugar: 4.9,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Pineapple",
    brand: "",
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
    sugar: 9.9,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Mango",
    brand: "",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    sugar: 13.7,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Watermelon",
    brand: "",
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    sugar: 6.2,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Cantaloupe",
    brand: "",
    calories: 34,
    protein: 0.8,
    carbs: 8.2,
    fat: 0.2,
    fiber: 0.9,
    sugar: 7.9,
    sodium: 0.016,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Honeydew Melon",
    brand: "",
    calories: 36,
    protein: 0.5,
    carbs: 9.1,
    fat: 0.1,
    fiber: 0.8,
    sugar: 8.1,
    sodium: 0.018,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Peach",
    brand: "",
    calories: 39,
    protein: 0.9,
    carbs: 9.5,
    fat: 0.3,
    fiber: 1.5,
    sugar: 8.4,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Pear",
    brand: "",
    calories: 57,
    protein: 0.4,
    carbs: 15,
    fat: 0.1,
    fiber: 3.1,
    sugar: 9.8,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Plum",
    brand: "",
    calories: 46,
    protein: 0.7,
    carbs: 11,
    fat: 0.3,
    fiber: 1.4,
    sugar: 9.9,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Cherries",
    brand: "",
    calories: 63,
    protein: 1.1,
    carbs: 16,
    fat: 0.2,
    fiber: 2.1,
    sugar: 12.8,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Grapefruit",
    brand: "",
    calories: 42,
    protein: 0.8,
    carbs: 11,
    fat: 0.1,
    fiber: 1.6,
    sugar: 6.9,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Kiwi",
    brand: "",
    calories: 61,
    protein: 1.1,
    carbs: 15,
    fat: 0.5,
    fiber: 3,
    sugar: 9,
    sodium: 0.003,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },
  {
    name: "Papaya",
    brand: "",
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.3,
    fiber: 1.7,
    sugar: 7.8,
    sodium: 0.008,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Fruits",
    source: "verified"
  },

  // ============= NUTS & SEEDS =============

  {
    name: "Almonds (raw)",
    brand: "",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 13,
    sugar: 4.4,
    sodium: 0.001,
    saturated_fat: 3.8,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Walnuts",
    brand: "",
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 0.002,
    saturated_fat: 6.1,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Cashews (raw)",
    brand: "",
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    fiber: 3.3,
    sugar: 5.9,
    sodium: 0.012,
    saturated_fat: 7.8,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Peanuts (raw)",
    brand: "",
    calories: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    fiber: 8.5,
    sugar: 4.7,
    sodium: 0.018,
    saturated_fat: 6.8,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Peanut Butter (Natural)",
    brand: "",
    calories: 589,
    protein: 24,
    carbs: 24,
    fat: 50,
    fiber: 8,
    sugar: 8,
    sodium: 0.017,
    saturated_fat: 10,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Almond Butter",
    brand: "",
    calories: 614,
    protein: 21,
    carbs: 19,
    fat: 56,
    fiber: 10,
    sugar: 4.4,
    sodium: 0.007,
    saturated_fat: 4.2,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Sunflower Seeds",
    brand: "",
    calories: 584,
    protein: 21,
    carbs: 20,
    fat: 51,
    fiber: 8.6,
    sugar: 2.6,
    sodium: 0.009,
    saturated_fat: 4.5,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Pumpkin Seeds",
    brand: "",
    calories: 559,
    protein: 19,
    carbs: 11,
    fat: 49,
    fiber: 6,
    sugar: 1.4,
    sodium: 0.007,
    saturated_fat: 8.7,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Chia Seeds",
    brand: "",
    calories: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    fiber: 34,
    sugar: 0,
    sodium: 0.016,
    saturated_fat: 3.3,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },
  {
    name: "Flax Seeds",
    brand: "",
    calories: 534,
    protein: 18,
    carbs: 29,
    fat: 42,
    fiber: 27,
    sugar: 1.6,
    sodium: 0.030,
    saturated_fat: 3.7,
    serving_size: "100g",
    category: "Nuts & Seeds",
    source: "verified"
  },

  // ============= LEGUMES =============

  {
    name: "Black Beans (cooked)",
    brand: "",
    calories: 132,
    protein: 8.9,
    carbs: 24,
    fat: 0.5,
    fiber: 8.7,
    sugar: 0.3,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },
  {
    name: "Kidney Beans (cooked)",
    brand: "",
    calories: 127,
    protein: 8.7,
    carbs: 23,
    fat: 0.5,
    fiber: 7.4,
    sugar: 0.3,
    sodium: 0.002,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },
  {
    name: "Chickpeas (cooked)",
    brand: "",
    calories: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    sodium: 0.007,
    saturated_fat: 0.3,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },
  {
    name: "Lentils (cooked)",
    brand: "",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    sugar: 1.8,
    sodium: 0.002,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },
  {
    name: "Pinto Beans (cooked)",
    brand: "",
    calories: 143,
    protein: 9,
    carbs: 26,
    fat: 0.7,
    fiber: 9,
    sugar: 0.3,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },
  {
    name: "Navy Beans (cooked)",
    brand: "",
    calories: 140,
    protein: 8.2,
    carbs: 26,
    fat: 0.6,
    fiber: 10.5,
    sugar: 0.4,
    sodium: 0,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },
  {
    name: "Green Peas (cooked)",
    brand: "",
    calories: 84,
    protein: 5.4,
    carbs: 16,
    fat: 0.2,
    fiber: 5.5,
    sugar: 5.9,
    sodium: 0.003,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },
  {
    name: "Edamame (cooked)",
    brand: "",
    calories: 122,
    protein: 11,
    carbs: 10,
    fat: 5.2,
    fiber: 5.2,
    sugar: 2.2,
    sodium: 0.005,
    saturated_fat: 0.6,
    serving_size: "100g",
    category: "Legumes",
    source: "verified"
  },

  // ============= OILS & FATS =============

  {
    name: "Olive Oil",
    brand: "",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0.002,
    saturated_fat: 14,
    serving_size: "100g",
    category: "Oils & Fats",
    source: "verified"
  },
  {
    name: "Coconut Oil",
    brand: "",
    calories: 862,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    saturated_fat: 87,
    serving_size: "100g",
    category: "Oils & Fats",
    source: "verified"
  },
  {
    name: "Butter",
    brand: "",
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    fiber: 0,
    sugar: 0.1,
    sodium: 0.011,
    saturated_fat: 51,
    serving_size: "100g",
    category: "Oils & Fats",
    source: "verified"
  },
  {
    name: "Canola Oil",
    brand: "",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    saturated_fat: 7,
    serving_size: "100g",
    category: "Oils & Fats",
    source: "verified"
  },
  {
    name: "Avocado Oil",
    brand: "",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    saturated_fat: 12,
    serving_size: "100g",
    category: "Oils & Fats",
    source: "verified"
  },

  // ============= BEVERAGES =============

  {
    name: "Orange Juice (100% pure)",
    brand: "",
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    sugar: 8.4,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Beverages",
    source: "verified"
  },
  {
    name: "Apple Juice (100% pure)",
    brand: "",
    calories: 46,
    protein: 0.1,
    carbs: 11.3,
    fat: 0.1,
    fiber: 0.2,
    sugar: 9.6,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Beverages",
    source: "verified"
  },
  {
    name: "Almond Milk (unsweetened)",
    brand: "",
    calories: 17,
    protein: 0.6,
    carbs: 0.6,
    fat: 1.5,
    fiber: 0.2,
    sugar: 0,
    sodium: 0.072,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Beverages",
    source: "verified"
  },
  {
    name: "Soy Milk",
    brand: "",
    calories: 54,
    protein: 3.3,
    carbs: 6,
    fat: 1.8,
    fiber: 0.6,
    sugar: 3.9,
    sodium: 0.051,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Beverages",
    source: "verified"
  },
  {
    name: "Oat Milk",
    brand: "",
    calories: 48,
    protein: 1.5,
    carbs: 7,
    fat: 1.5,
    fiber: 0.8,
    sugar: 4,
    sodium: 0.048,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Beverages",
    source: "verified"
  },

  // ============= CONDIMENTS & SAUCES =============

  {
    name: "Ketchup",
    brand: "",
    calories: 112,
    protein: 1.1,
    carbs: 27,
    fat: 0.3,
    fiber: 0.3,
    sugar: 22,
    sodium: 0.907,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "Mustard (Yellow)",
    brand: "",
    calories: 60,
    protein: 3.7,
    carbs: 5.8,
    fat: 3.3,
    fiber: 3.2,
    sugar: 1.3,
    sodium: 1.120,
    saturated_fat: 0.2,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "Mayonnaise",
    brand: "",
    calories: 680,
    protein: 1,
    carbs: 0.6,
    fat: 75,
    fiber: 0,
    sugar: 0.6,
    sodium: 0.635,
    saturated_fat: 11,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "Soy Sauce",
    brand: "",
    calories: 53,
    protein: 5.5,
    carbs: 4.9,
    fat: 0.5,
    fiber: 0.4,
    sugar: 0.4,
    sodium: 5.493,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "Hot Sauce (Tabasco)",
    brand: "",
    calories: 12,
    protein: 0.8,
    carbs: 0.8,
    fat: 0.8,
    fiber: 0.6,
    sugar: 0.1,
    sodium: 0.633,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "BBQ Sauce",
    brand: "",
    calories: 172,
    protein: 0.8,
    carbs: 41,
    fat: 0.7,
    fiber: 0.8,
    sugar: 33,
    sodium: 1.025,
    saturated_fat: 0.1,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "Ranch Dressing",
    brand: "",
    calories: 430,
    protein: 1.4,
    carbs: 5.5,
    fat: 45,
    fiber: 0.2,
    sugar: 4.3,
    sodium: 0.750,
    saturated_fat: 7,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "Honey",
    brand: "",
    calories: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
    sugar: 82,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },
  {
    name: "Maple Syrup",
    brand: "",
    calories: 260,
    protein: 0,
    carbs: 67,
    fat: 0.1,
    fiber: 0,
    sugar: 60,
    sodium: 0.012,
    saturated_fat: 0,
    serving_size: "100g",
    category: "Condiments",
    source: "verified"
  },

  // ============= SNACKS & PROCESSED =============

  {
    name: "Potato Chips",
    brand: "",
    calories: 536,
    protein: 7,
    carbs: 53,
    fat: 35,
    fiber: 3.4,
    sugar: 0.2,
    sodium: 0.570,
    saturated_fat: 3.3,
    serving_size: "100g",
    category: "Snacks",
    source: "verified"
  },
  {
    name: "Pretzels",
    brand: "",
    calories: 380,
    protein: 10,
    carbs: 80,
    fat: 3,
    fiber: 3,
    sugar: 2.2,
    sodium: 1.350,
    saturated_fat: 0.7,
    serving_size: "100g",
    category: "Snacks",
    source: "verified"
  },
  {
    name: "Popcorn (air-popped)",
    brand: "",
    calories: 387,
    protein: 13,
    carbs: 78,
    fat: 4.5,
    fiber: 15,
    sugar: 0.9,
    sodium: 0.008,
    saturated_fat: 0.6,
    serving_size: "100g",
    category: "Snacks",
    source: "verified"
  },
  {
    name: "Crackers (Saltines)",
    brand: "",
    calories: 418,
    protein: 9,
    carbs: 74,
    fat: 8.5,
    fiber: 3,
    sugar: 2.2,
    sodium: 1.080,
    saturated_fat: 1.5,
    serving_size: "100g",
    category: "Snacks",
    source: "verified"
  },
  {
    name: "Granola Bar",
    brand: "",
    calories: 471,
    protein: 10,
    carbs: 64,
    fat: 20,
    fiber: 5.7,
    sugar: 24,
    sodium: 0.230,
    saturated_fat: 7,
    serving_size: "100g",
    category: "Snacks",
    source: "verified"
  },
  {
    name: "Dark Chocolate (70-85% cacao)",
    brand: "",
    calories: 598,
    protein: 7.8,
    carbs: 46,
    fat: 43,
    fiber: 11,
    sugar: 24,
    sodium: 0.020,
    saturated_fat: 25,
    serving_size: "100g",
    category: "Snacks",
    source: "verified"
  },
  {
    name: "Milk Chocolate",
    brand: "",
    calories: 535,
    protein: 7.7,
    carbs: 59,
    fat: 30,
    fiber: 3.4,
    sugar: 52,
    sodium: 0.079,
    saturated_fat: 19,
    serving_size: "100g",
    category: "Snacks",
    source: "verified"
  },

  // ============= SUPPLEMENTS & PROTEIN POWDERS =============

  {
    name: "Whey Protein Powder",
    brand: "",
    calories: 400,
    protein: 80,
    carbs: 8,
    fat: 4,
    fiber: 0,
    sugar: 4,
    sodium: 0.150,
    saturated_fat: 2,
    serving_size: "100g",
    category: "Supplements",
    source: "verified"
  },
  {
    name: "Casein Protein Powder",
    brand: "",
    calories: 380,
    protein: 82,
    carbs: 10,
    fat: 1.5,
    fiber: 0,
    sugar: 3,
    sodium: 0.120,
    saturated_fat: 0.5,
    serving_size: "100g",
    category: "Supplements",
    source: "verified"
  },
  {
    name: "Plant-Based Protein Powder",
    brand: "",
    calories: 375,
    protein: 75,
    carbs: 10,
    fat: 5,
    fiber: 5,
    sugar: 1,
    sodium: 0.400,
    saturated_fat: 1,
    serving_size: "100g",
    category: "Supplements",
    source: "verified"
  }
];

// Function to get all categories
export const getFoodCategories = () => {
  const categories = new Set(comprehensiveFoods.map(food => food.category));
  return Array.from(categories).sort();
};

// Function to get foods by category
export const getFoodsByCategory = (category) => {
  return comprehensiveFoods.filter(food => food.category === category);
};

// Function to search foods
export const searchComprehensiveFoods = (query) => {
  const searchTerm = query.toLowerCase();
  return comprehensiveFoods.filter(food =>
    food.name.toLowerCase().includes(searchTerm) ||
    (food.brand && food.brand.toLowerCase().includes(searchTerm)) ||
    (food.category && food.category.toLowerCase().includes(searchTerm))
  );
};