/**
 * Curated Fitness Meals Database
 *
 * Common, practical fitness meals that people actually eat
 * No desserts, no weird foods - just real meal prep staples
 */

export const CURATED_FITNESS_MEALS = [
  // CHICKEN MEALS
  {
    id: 'curated_chicken_rice_broccoli',
    name: 'Grilled Chicken with Rice & Broccoli',
    category: 'Chicken',
    area: 'American',
    mealType: 'lunch',
    tags: ['high-protein', 'meal-prep', 'clean-eating'],
    featured: true, // MOST POPULAR - Classic meal prep staple
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    readyInMinutes: 30,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    ingredients: [
      { food: { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 200, unit: 'g', original: '200g Chicken Breast' },
      { food: { name: 'Brown Rice', calories: 111, protein: 2.6, carbs: 23, fat: 0.9 }, quantity: 150, unit: 'g', original: '150g Brown Rice' },
      { food: { name: 'Broccoli', calories: 34, protein: 2.8, carbs: 7, fat: 0.4 }, quantity: 100, unit: 'g', original: '100g Broccoli' },
    ],
    instructions: [
      'Season chicken breast with salt, pepper, and garlic powder',
      'Grill chicken for 6-7 minutes per side until cooked through',
      'Cook brown rice according to package directions',
      'Steam broccoli for 5 minutes until tender',
      'Plate chicken, rice, and broccoli together'
    ],
    nutrition: { calories: 520, protein: 54, carbs: 48, fat: 8 },
    source: 'curated',
  },

  // TURKEY MEALS
  {
    id: 'curated_turkey_avocado_sandwich',
    name: 'Turkey & Avocado Sandwich',
    category: 'Starter',
    area: 'American',
    mealType: 'lunch',
    tags: ['quick', 'portable', 'balanced'],
    featured: true, // MOST POPULAR - Classic sandwich
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 5,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400',
    ingredients: [
      { food: { name: 'Whole Wheat Bread', calories: 247, protein: 13, carbs: 41, fat: 3.4 }, quantity: 60, unit: 'g', original: '2 slices Whole Wheat Bread' },
      { food: { name: 'Turkey Breast', calories: 104, protein: 24, carbs: 0, fat: 0.7 }, quantity: 100, unit: 'g', original: '100g Sliced Turkey Breast' },
      { food: { name: 'Avocado', calories: 160, protein: 2, carbs: 8.5, fat: 14.7 }, quantity: 50, unit: 'g', original: '1/2 Avocado' },
      { food: { name: 'Lettuce', calories: 5, protein: 0.5, carbs: 1, fat: 0 }, quantity: 20, unit: 'g', original: '2 leaves Lettuce' },
      { food: { name: 'Tomato', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 50, unit: 'g', original: '2 slices Tomato' },
    ],
    instructions: [
      'Toast bread slices if desired',
      'Mash avocado and spread on one slice',
      'Layer turkey, lettuce, and tomato',
      'Top with second bread slice and cut in half'
    ],
    nutrition: { calories: 420, protein: 42, carbs: 45, fat: 15 },
    source: 'curated',
  },

  // SALMON MEALS
  {
    id: 'curated_salmon_sweet_potato',
    name: 'Baked Salmon with Sweet Potato',
    category: 'Seafood',
    area: 'American',
    mealType: 'dinner',
    tags: ['high-protein', 'omega-3', 'nutrient-dense'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '25 minutes',
    readyInMinutes: 35,
    difficulty: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    ingredients: [
      { food: { name: 'Salmon Fillet', calories: 208, protein: 20, carbs: 0, fat: 13 }, quantity: 180, unit: 'g', original: '180g Salmon Fillet' },
      { food: { name: 'Sweet Potato', calories: 86, protein: 1.6, carbs: 20, fat: 0.1 }, quantity: 200, unit: 'g', original: '1 Medium Sweet Potato' },
      { food: { name: 'Asparagus', calories: 20, protein: 2.2, carbs: 3.9, fat: 0.1 }, quantity: 100, unit: 'g', original: '100g Asparagus' },
      { food: { name: 'Olive Oil', calories: 119, protein: 0, carbs: 0, fat: 13.5 }, quantity: 10, unit: 'ml', original: '1 tbsp Olive Oil' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C)',
      'Cut sweet potato into wedges and toss with half the olive oil',
      'Bake sweet potato for 20 minutes',
      'Season salmon with lemon, salt, and pepper',
      'Add salmon and asparagus to oven, drizzle with remaining oil',
      'Bake for 12-15 minutes until salmon is cooked through'
    ],
    nutrition: { calories: 600, protein: 42, carbs: 50, fat: 28 },
    source: 'curated',
  },

  // PASTA MEALS
  {
    id: 'curated_chicken_pasta',
    name: 'Chicken & Veggie Pasta',
    category: 'Pasta',
    area: 'Italian',
    mealType: 'dinner',
    tags: ['balanced', 'filling', 'protein-rich'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    readyInMinutes: 30,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    ingredients: [
      { food: { name: 'Whole Wheat Pasta', calories: 174, protein: 7.5, carbs: 37, fat: 0.8 }, quantity: 80, unit: 'g', original: '80g Whole Wheat Pasta' },
      { food: { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 150, unit: 'g', original: '150g Chicken Breast' },
      { food: { name: 'Bell Peppers', calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 }, quantity: 100, unit: 'g', original: '1 Bell Pepper' },
      { food: { name: 'Zucchini', calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3 }, quantity: 100, unit: 'g', original: '1 small Zucchini' },
      { food: { name: 'Tomato Sauce', calories: 24, protein: 1.2, carbs: 4.7, fat: 0.3 }, quantity: 100, unit: 'ml', original: '100ml Tomato Sauce' },
    ],
    instructions: [
      'Cook pasta according to package directions',
      'Dice chicken and cook in pan with olive oil',
      'Add chopped peppers and zucchini, sauté for 5 minutes',
      'Add tomato sauce and simmer',
      'Toss cooked pasta with chicken and veggies'
    ],
    nutrition: { calories: 580, protein: 53, carbs: 65, fat: 10 },
    source: 'curated',
  },

  // BEEF MEALS
  {
    id: 'curated_lean_beef_quinoa_bowl',
    name: 'Lean Beef & Quinoa Bowl',
    category: 'Beef',
    area: 'American',
    mealType: 'dinner',
    tags: ['high-protein', 'bowl', 'nutrient-dense'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '25 minutes',
    readyInMinutes: 35,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    ingredients: [
      { food: { name: 'Lean Ground Beef (93/7)', calories: 176, protein: 21, carbs: 0, fat: 10 }, quantity: 150, unit: 'g', original: '150g Lean Ground Beef' },
      { food: { name: 'Quinoa', calories: 120, protein: 4.4, carbs: 21, fat: 1.9 }, quantity: 100, unit: 'g', original: '100g Cooked Quinoa' },
      { food: { name: 'Black Beans', calories: 132, protein: 8.9, carbs: 24, fat: 0.5 }, quantity: 100, unit: 'g', original: '100g Black Beans' },
      { food: { name: 'Corn', calories: 96, protein: 3.4, carbs: 21, fat: 1.5 }, quantity: 80, unit: 'g', original: '80g Corn' },
      { food: { name: 'Salsa', calories: 15, protein: 0.5, carbs: 3, fat: 0 }, quantity: 50, unit: 'ml', original: '50ml Salsa' },
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Brown ground beef in a pan with taco seasoning',
      'Warm black beans and corn',
      'Assemble bowl with quinoa as base',
      'Top with beef, beans, corn, and salsa'
    ],
    nutrition: { calories: 620, protein: 48, carbs: 70, fat: 16 },
    source: 'curated',
  },

  // VEGETARIAN MEALS
  {
    id: 'curated_greek_chickpea_salad',
    name: 'Greek Chickpea Salad',
    category: 'Vegetarian',
    area: 'Greek',
    mealType: 'lunch',
    tags: ['vegetarian', 'high-fiber', 'refreshing'],
    featured: true, // MOST POPULAR - Fresh & healthy
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 10,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    ingredients: [
      { food: { name: 'Chickpeas', calories: 164, protein: 8.9, carbs: 27, fat: 2.6 }, quantity: 200, unit: 'g', original: '200g Chickpeas' },
      { food: { name: 'Cucumber', calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1 }, quantity: 150, unit: 'g', original: '1 Cucumber' },
      { food: { name: 'Cherry Tomatoes', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 100, unit: 'g', original: '100g Cherry Tomatoes' },
      { food: { name: 'Feta Cheese', calories: 264, protein: 14, carbs: 4, fat: 21 }, quantity: 50, unit: 'g', original: '50g Feta Cheese' },
      { food: { name: 'Olive Oil', calories: 119, protein: 0, carbs: 0, fat: 13.5 }, quantity: 10, unit: 'ml', original: '1 tbsp Olive Oil' },
      { food: { name: 'Lemon Juice', calories: 11, protein: 0.2, carbs: 3.7, fat: 0.1 }, quantity: 15, unit: 'ml', original: '1 tbsp Lemon Juice' },
    ],
    instructions: [
      'Drain and rinse chickpeas',
      'Chop cucumber and halve cherry tomatoes',
      'Crumble feta cheese',
      'Mix all ingredients in a bowl',
      'Dress with olive oil, lemon juice, salt, and oregano'
    ],
    nutrition: { calories: 450, protein: 22, carbs: 42, fat: 24 },
    source: 'curated',
  },

  // BREAKFAST MEALS
  {
    id: 'curated_protein_oatmeal',
    name: 'High-Protein Oatmeal Bowl',
    category: 'Breakfast',
    area: 'American',
    mealType: 'breakfast',
    tags: ['high-protein', 'filling', 'energizing'],
    featured: true, // MOST POPULAR - #1 breakfast choice
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '5 minutes',
    readyInMinutes: 10,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=400',
    ingredients: [
      { food: { name: 'Rolled Oats', calories: 389, protein: 16.9, carbs: 66, fat: 6.9 }, quantity: 60, unit: 'g', original: '60g Rolled Oats' },
      { food: { name: 'Protein Powder', calories: 120, protein: 24, carbs: 3, fat: 1.5 }, quantity: 30, unit: 'g', original: '1 scoop Protein Powder' },
      { food: { name: 'Banana', calories: 89, protein: 1.1, carbs: 23, fat: 0.3 }, quantity: 100, unit: 'g', original: '1 Banana' },
      { food: { name: 'Almond Butter', calories: 98, protein: 3.4, carbs: 3, fat: 9 }, quantity: 15, unit: 'g', original: '1 tbsp Almond Butter' },
      { food: { name: 'Blueberries', calories: 57, protein: 0.7, carbs: 14, fat: 0.3 }, quantity: 50, unit: 'g', original: '50g Blueberries' },
    ],
    instructions: [
      'Cook oats with water or milk according to package',
      'Mix in protein powder while oats are hot',
      'Slice banana and add on top',
      'Add dollop of almond butter',
      'Top with blueberries and enjoy'
    ],
    nutrition: { calories: 480, protein: 35, carbs: 68, fat: 12 },
    source: 'curated',
  },

  {
    id: 'curated_egg_veggie_scramble',
    name: 'Veggie Egg Scramble',
    category: 'Breakfast',
    area: 'American',
    mealType: 'breakfast',
    tags: ['high-protein', 'quick', 'low-carb'],
    featured: true, // MOST POPULAR - Quick breakfast
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '8 minutes',
    readyInMinutes: 13,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400',
    ingredients: [
      { food: { name: 'Eggs', calories: 155, protein: 13, carbs: 1, fat: 11 }, quantity: 150, unit: 'g', original: '3 Large Eggs' },
      { food: { name: 'Spinach', calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 }, quantity: 50, unit: 'g', original: '1 cup Spinach' },
      { food: { name: 'Bell Peppers', calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 }, quantity: 50, unit: 'g', original: '1/2 Bell Pepper' },
      { food: { name: 'Mushrooms', calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3 }, quantity: 50, unit: 'g', original: '50g Mushrooms' },
      { food: { name: 'Cheese', calories: 113, protein: 7, carbs: 0.9, fat: 9.3 }, quantity: 30, unit: 'g', original: '30g Shredded Cheese' },
    ],
    instructions: [
      'Whisk eggs in a bowl',
      'Sauté chopped veggies in a pan for 3-4 minutes',
      'Pour eggs over veggies',
      'Scramble until eggs are cooked',
      'Top with cheese and let melt'
    ],
    nutrition: { calories: 360, protein: 30, carbs: 15, fat: 22 },
    source: 'curated',
  },

  // SNACKS
  {
    id: 'curated_protein_smoothie',
    name: 'Post-Workout Protein Smoothie',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['high-protein', 'quick', 'post-workout'],
    featured: true, // MOST POPULAR - Classic post-workout favorite
    servings: 1,
    prepTime: '3 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 3,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    ingredients: [
      { food: { name: 'Protein Powder', calories: 120, protein: 24, carbs: 3, fat: 1.5 }, quantity: 30, unit: 'g', original: '1 scoop Protein Powder' },
      { food: { name: 'Banana', calories: 89, protein: 1.1, carbs: 23, fat: 0.3 }, quantity: 100, unit: 'g', original: '1 Banana' },
      { food: { name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fat: 0.4 }, quantity: 100, unit: 'g', original: '100g Greek Yogurt' },
      { food: { name: 'Almond Milk', calories: 15, protein: 0.6, carbs: 0.6, fat: 1.1 }, quantity: 200, unit: 'ml', original: '200ml Almond Milk' },
      { food: { name: 'Peanut Butter', calories: 94, protein: 4, carbs: 3.1, fat: 8 }, quantity: 10, unit: 'g', original: '1 tsp Peanut Butter' },
    ],
    instructions: [
      'Add all ingredients to blender',
      'Blend until smooth',
      'Add ice if desired',
      'Pour into glass and enjoy'
    ],
    nutrition: { calories: 280, protein: 38, carbs: 28, fat: 6 },
    source: 'curated',
  },

  {
    id: 'curated_tuna_crackers',
    name: 'Tuna & Whole Grain Crackers',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['high-protein', 'portable', 'quick'],
    servings: 1,
    prepTime: '3 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 3,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1625938145312-754af8f256b0?w=400',
    ingredients: [
      { food: { name: 'Tuna (canned in water)', calories: 116, protein: 26, carbs: 0, fat: 0.8 }, quantity: 100, unit: 'g', original: '1 can Tuna' },
      { food: { name: 'Whole Grain Crackers', calories: 120, protein: 3, carbs: 20, fat: 3 }, quantity: 30, unit: 'g', original: '10 crackers' },
      { food: { name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fat: 0.4 }, quantity: 50, unit: 'g', original: '2 tbsp Greek Yogurt' },
    ],
    instructions: [
      'Drain tuna well',
      'Mix tuna with Greek yogurt',
      'Season with salt, pepper, and lemon',
      'Serve with whole grain crackers'
    ],
    nutrition: { calories: 260, protein: 38, carbs: 22, fat: 4 },
    source: 'curated',
  },

  // MORE CHICKEN MEALS
  {
    id: 'curated_chicken_burrito_bowl',
    name: 'Chicken Burrito Bowl',
    category: 'Chicken',
    area: 'Mexican',
    mealType: 'lunch',
    tags: ['high-protein', 'bowl', 'meal-prep'],
    featured: true, // MOST POPULAR - Very popular meal prep choice
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    readyInMinutes: 30,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
    ingredients: [
      { food: { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 180, unit: 'g', original: '180g Chicken Breast' },
      { food: { name: 'Brown Rice', calories: 111, protein: 2.6, carbs: 23, fat: 0.9 }, quantity: 150, unit: 'g', original: '150g Brown Rice' },
      { food: { name: 'Black Beans', calories: 132, protein: 8.9, carbs: 24, fat: 0.5 }, quantity: 80, unit: 'g', original: '80g Black Beans' },
      { food: { name: 'Corn', calories: 96, protein: 3.4, carbs: 21, fat: 1.5 }, quantity: 60, unit: 'g', original: '60g Corn' },
      { food: { name: 'Avocado', calories: 160, protein: 2, carbs: 8.5, fat: 14.7 }, quantity: 40, unit: 'g', original: '1/4 Avocado' },
      { food: { name: 'Salsa', calories: 15, protein: 0.5, carbs: 3, fat: 0 }, quantity: 50, unit: 'ml', original: '50ml Salsa' },
    ],
    instructions: [
      'Season and grill chicken with taco spices',
      'Cook brown rice according to package',
      'Warm black beans and corn',
      'Assemble bowl: rice, beans, corn, sliced chicken',
      'Top with avocado and salsa'
    ],
    nutrition: { calories: 650, protein: 56, carbs: 72, fat: 16 },
    source: 'curated',
  },

  {
    id: 'curated_chicken_stir_fry',
    name: 'Chicken & Veggie Stir Fry',
    category: 'Chicken',
    area: 'Chinese',
    mealType: 'dinner',
    tags: ['high-protein', 'quick', 'low-carb'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '12 minutes',
    readyInMinutes: 22,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    ingredients: [
      { food: { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 200, unit: 'g', original: '200g Chicken Breast' },
      { food: { name: 'Broccoli', calories: 34, protein: 2.8, carbs: 7, fat: 0.4 }, quantity: 100, unit: 'g', original: '100g Broccoli' },
      { food: { name: 'Bell Peppers', calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 }, quantity: 100, unit: 'g', original: '1 Bell Pepper' },
      { food: { name: 'Snow Peas', calories: 42, protein: 2.8, carbs: 7.6, fat: 0.2 }, quantity: 80, unit: 'g', original: '80g Snow Peas' },
      { food: { name: 'Soy Sauce', calories: 11, protein: 1.3, carbs: 1, fat: 0 }, quantity: 20, unit: 'ml', original: '20ml Soy Sauce' },
      { food: { name: 'Brown Rice', calories: 111, protein: 2.6, carbs: 23, fat: 0.9 }, quantity: 120, unit: 'g', original: '120g Brown Rice' },
    ],
    instructions: [
      'Cook brown rice according to package',
      'Slice chicken into strips',
      'Heat wok or large pan with a bit of oil',
      'Stir-fry chicken until cooked through',
      'Add veggies and stir-fry for 5 minutes',
      'Add soy sauce and serve over rice'
    ],
    nutrition: { calories: 550, protein: 52, carbs: 58, fat: 9 },
    source: 'curated',
  },

  // MORE TURKEY MEALS
  {
    id: 'curated_turkey_chili',
    name: 'Lean Turkey Chili',
    category: 'Starter',
    area: 'American',
    mealType: 'dinner',
    tags: ['high-protein', 'comfort-food', 'meal-prep'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '30 minutes',
    readyInMinutes: 40,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1583663824728-f0e5b15db58a?w=400',
    ingredients: [
      { food: { name: 'Ground Turkey (93/7)', calories: 170, protein: 21, carbs: 0, fat: 9 }, quantity: 180, unit: 'g', original: '180g Ground Turkey' },
      { food: { name: 'Kidney Beans', calories: 127, protein: 8.7, carbs: 23, fat: 0.5 }, quantity: 150, unit: 'g', original: '150g Kidney Beans' },
      { food: { name: 'Diced Tomatoes', calories: 32, protein: 1.6, carbs: 7, fat: 0.3 }, quantity: 200, unit: 'g', original: '200g Diced Tomatoes' },
      { food: { name: 'Bell Peppers', calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 }, quantity: 80, unit: 'g', original: '1 small Bell Pepper' },
      { food: { name: 'Onion', calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1 }, quantity: 60, unit: 'g', original: '1/2 Onion' },
    ],
    instructions: [
      'Brown ground turkey in a large pot',
      'Add diced onion and pepper, sauté for 5 minutes',
      'Add tomatoes, beans, and chili spices',
      'Simmer for 25-30 minutes',
      'Serve hot, optionally with Greek yogurt on top'
    ],
    nutrition: { calories: 520, protein: 48, carbs: 58, fat: 12 },
    source: 'curated',
  },

  // MORE BEEF MEALS
  {
    id: 'curated_beef_stir_fry',
    name: 'Lean Beef & Broccoli',
    category: 'Beef',
    area: 'Chinese',
    mealType: 'dinner',
    tags: ['high-protein', 'quick', 'asian'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    readyInMinutes: 25,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    ingredients: [
      { food: { name: 'Lean Beef Sirloin', calories: 180, protein: 26, carbs: 0, fat: 8 }, quantity: 180, unit: 'g', original: '180g Lean Beef' },
      { food: { name: 'Broccoli', calories: 34, protein: 2.8, carbs: 7, fat: 0.4 }, quantity: 150, unit: 'g', original: '150g Broccoli' },
      { food: { name: 'Brown Rice', calories: 111, protein: 2.6, carbs: 23, fat: 0.9 }, quantity: 150, unit: 'g', original: '150g Brown Rice' },
      { food: { name: 'Soy Sauce', calories: 11, protein: 1.3, carbs: 1, fat: 0 }, quantity: 20, unit: 'ml', original: '2 tbsp Soy Sauce' },
      { food: { name: 'Garlic', calories: 4, protein: 0.2, carbs: 1, fat: 0 }, quantity: 5, unit: 'g', original: '1 clove Garlic' },
    ],
    instructions: [
      'Cook brown rice according to package',
      'Slice beef thinly against the grain',
      'Stir-fry beef in hot wok until browned',
      'Remove beef, add broccoli and stir-fry',
      'Return beef, add soy sauce and garlic',
      'Serve over brown rice'
    ],
    nutrition: { calories: 580, protein: 48, carbs: 54, fat: 14 },
    source: 'curated',
  },

  // MORE SEAFOOD MEALS
  {
    id: 'curated_shrimp_tacos',
    name: 'Grilled Shrimp Tacos',
    category: 'Seafood',
    area: 'Mexican',
    mealType: 'lunch',
    tags: ['high-protein', 'quick', 'fresh'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '8 minutes',
    readyInMinutes: 18,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    ingredients: [
      { food: { name: 'Shrimp', calories: 99, protein: 24, carbs: 0, fat: 0.3 }, quantity: 180, unit: 'g', original: '180g Shrimp' },
      { food: { name: 'Corn Tortillas', calories: 104, protein: 2.7, carbs: 22, fat: 1.1 }, quantity: 60, unit: 'g', original: '3 Corn Tortillas' },
      { food: { name: 'Cabbage Slaw', calories: 25, protein: 1.3, carbs: 6, fat: 0.1 }, quantity: 80, unit: 'g', original: '80g Cabbage Slaw' },
      { food: { name: 'Avocado', calories: 160, protein: 2, carbs: 8.5, fat: 14.7 }, quantity: 40, unit: 'g', original: '1/4 Avocado' },
      { food: { name: 'Lime Juice', calories: 10, protein: 0.2, carbs: 3.3, fat: 0 }, quantity: 15, unit: 'ml', original: '1 tbsp Lime Juice' },
    ],
    instructions: [
      'Season shrimp with chili powder and lime',
      'Grill shrimp for 2-3 minutes per side',
      'Warm tortillas',
      'Assemble tacos with slaw, shrimp, and avocado',
      'Squeeze lime juice over top'
    ],
    nutrition: { calories: 420, protein: 45, carbs: 42, fat: 10 },
    source: 'curated',
  },

  {
    id: 'curated_tuna_salad',
    name: 'Mediterranean Tuna Salad',
    category: 'Seafood',
    area: 'Mediterranean',
    mealType: 'lunch',
    tags: ['high-protein', 'fresh', 'no-cook'],
    servings: 1,
    prepTime: '8 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 8,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    ingredients: [
      { food: { name: 'Tuna (canned in water)', calories: 116, protein: 26, carbs: 0, fat: 0.8 }, quantity: 150, unit: 'g', original: '150g Tuna' },
      { food: { name: 'Mixed Greens', calories: 23, protein: 2.4, carbs: 4.3, fat: 0.4 }, quantity: 100, unit: 'g', original: '2 cups Mixed Greens' },
      { food: { name: 'Cherry Tomatoes', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 100, unit: 'g', original: '100g Cherry Tomatoes' },
      { food: { name: 'Cucumber', calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1 }, quantity: 100, unit: 'g', original: '1/2 Cucumber' },
      { food: { name: 'Olives', calories: 115, protein: 0.8, carbs: 6.3, fat: 10.7 }, quantity: 30, unit: 'g', original: '10 Olives' },
      { food: { name: 'Olive Oil', calories: 119, protein: 0, carbs: 0, fat: 13.5 }, quantity: 10, unit: 'ml', original: '1 tbsp Olive Oil' },
    ],
    instructions: [
      'Drain tuna and flake into large bowl',
      'Chop vegetables',
      'Add greens, tomatoes, cucumber, and olives',
      'Drizzle with olive oil and lemon juice',
      'Toss and season with salt and pepper'
    ],
    nutrition: { calories: 380, protein: 42, carbs: 20, fat: 16 },
    source: 'curated',
  },

  // MORE VEGETARIAN MEALS
  {
    id: 'curated_lentil_curry',
    name: 'Red Lentil Curry',
    category: 'Vegetarian',
    area: 'Indian',
    mealType: 'dinner',
    tags: ['vegetarian', 'high-protein', 'comfort-food'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '25 minutes',
    readyInMinutes: 35,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
    ingredients: [
      { food: { name: 'Red Lentils', calories: 116, protein: 9, carbs: 20, fat: 0.4 }, quantity: 120, unit: 'g', original: '120g Red Lentils' },
      { food: { name: 'Coconut Milk (light)', calories: 150, protein: 1.5, carbs: 6, fat: 14 }, quantity: 100, unit: 'ml', original: '100ml Coconut Milk' },
      { food: { name: 'Spinach', calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 }, quantity: 80, unit: 'g', original: '80g Spinach' },
      { food: { name: 'Tomatoes', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 100, unit: 'g', original: '1 Tomato' },
      { food: { name: 'Brown Rice', calories: 111, protein: 2.6, carbs: 23, fat: 0.9 }, quantity: 150, unit: 'g', original: '150g Brown Rice' },
    ],
    instructions: [
      'Cook brown rice according to package',
      'Sauté onions and curry spices',
      'Add lentils, tomatoes, and vegetable broth',
      'Simmer for 20 minutes until lentils are tender',
      'Stir in coconut milk and spinach',
      'Serve over brown rice'
    ],
    nutrition: { calories: 520, protein: 24, carbs: 78, fat: 12 },
    source: 'curated',
  },

  {
    id: 'curated_quinoa_buddha_bowl',
    name: 'Quinoa Buddha Bowl',
    category: 'Vegetarian',
    area: 'American',
    mealType: 'lunch',
    tags: ['vegetarian', 'bowl', 'nutrient-dense'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    readyInMinutes: 30,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    ingredients: [
      { food: { name: 'Quinoa', calories: 120, protein: 4.4, carbs: 21, fat: 1.9 }, quantity: 120, unit: 'g', original: '120g Cooked Quinoa' },
      { food: { name: 'Chickpeas', calories: 164, protein: 8.9, carbs: 27, fat: 2.6 }, quantity: 100, unit: 'g', original: '100g Chickpeas' },
      { food: { name: 'Sweet Potato', calories: 86, protein: 1.6, carbs: 20, fat: 0.1 }, quantity: 150, unit: 'g', original: '150g Sweet Potato' },
      { food: { name: 'Kale', calories: 33, protein: 2.9, carbs: 6, fat: 0.9 }, quantity: 60, unit: 'g', original: '60g Kale' },
      { food: { name: 'Avocado', calories: 160, protein: 2, carbs: 8.5, fat: 14.7 }, quantity: 50, unit: 'g', original: '1/3 Avocado' },
      { food: { name: 'Tahini', calories: 89, protein: 2.6, carbs: 3.2, fat: 8 }, quantity: 15, unit: 'g', original: '1 tbsp Tahini' },
    ],
    instructions: [
      'Cook quinoa according to package',
      'Roast sweet potato cubes at 400°F for 20 minutes',
      'Massage kale with a bit of lemon juice',
      'Warm chickpeas with spices',
      'Assemble bowl: quinoa, sweet potato, chickpeas, kale',
      'Top with avocado and drizzle tahini dressing'
    ],
    nutrition: { calories: 580, protein: 22, carbs: 78, fat: 22 },
    source: 'curated',
  },

  // MORE BREAKFAST MEALS
  {
    id: 'curated_protein_pancakes',
    name: 'Protein Pancakes',
    category: 'Breakfast',
    area: 'American',
    mealType: 'breakfast',
    tags: ['high-protein', 'sweet', 'filling'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '10 minutes',
    readyInMinutes: 15,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
    ingredients: [
      { food: { name: 'Banana', calories: 89, protein: 1.1, carbs: 23, fat: 0.3 }, quantity: 100, unit: 'g', original: '1 Banana' },
      { food: { name: 'Eggs', calories: 155, protein: 13, carbs: 1, fat: 11 }, quantity: 100, unit: 'g', original: '2 Eggs' },
      { food: { name: 'Protein Powder', calories: 120, protein: 24, carbs: 3, fat: 1.5 }, quantity: 30, unit: 'g', original: '1 scoop Protein Powder' },
      { food: { name: 'Oat Flour', calories: 110, protein: 4, carbs: 18, fat: 2 }, quantity: 30, unit: 'g', original: '30g Oat Flour' },
      { food: { name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fat: 0.4 }, quantity: 50, unit: 'g', original: '50g Greek Yogurt (topping)' },
      { food: { name: 'Berries', calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3 }, quantity: 50, unit: 'g', original: '50g Mixed Berries' },
    ],
    instructions: [
      'Mash banana in a bowl',
      'Add eggs, protein powder, and oat flour',
      'Mix until smooth batter forms',
      'Cook pancakes on non-stick griddle',
      'Top with Greek yogurt and berries'
    ],
    nutrition: { calories: 480, protein: 48, carbs: 52, fat: 12 },
    source: 'curated',
  },

  {
    id: 'curated_avocado_toast',
    name: 'Avocado Toast with Egg',
    category: 'Breakfast',
    area: 'American',
    mealType: 'breakfast',
    tags: ['quick', 'fresh', 'balanced'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '5 minutes',
    readyInMinutes: 10,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
    ingredients: [
      { food: { name: 'Whole Wheat Bread', calories: 247, protein: 13, carbs: 41, fat: 3.4 }, quantity: 60, unit: 'g', original: '2 slices Whole Wheat Bread' },
      { food: { name: 'Avocado', calories: 160, protein: 2, carbs: 8.5, fat: 14.7 }, quantity: 80, unit: 'g', original: '1/2 Avocado' },
      { food: { name: 'Eggs', calories: 155, protein: 13, carbs: 1, fat: 11 }, quantity: 100, unit: 'g', original: '2 Eggs' },
      { food: { name: 'Cherry Tomatoes', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 50, unit: 'g', original: '50g Cherry Tomatoes' },
    ],
    instructions: [
      'Toast bread slices',
      'Mash avocado with salt and pepper',
      'Fry or poach eggs',
      'Spread avocado on toast',
      'Top with eggs and halved cherry tomatoes'
    ],
    nutrition: { calories: 520, protein: 30, carbs: 52, fat: 24 },
    source: 'curated',
  },

  // MORE SNACKS
  {
    id: 'curated_cottage_cheese_bowl',
    name: 'Cottage Cheese & Fruit Bowl',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['high-protein', 'quick', 'refreshing'],
    servings: 1,
    prepTime: '3 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 3,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    ingredients: [
      { food: { name: 'Cottage Cheese (low-fat)', calories: 72, protein: 12, carbs: 6, fat: 1 }, quantity: 150, unit: 'g', original: '150g Cottage Cheese' },
      { food: { name: 'Pineapple', calories: 50, protein: 0.5, carbs: 13, fat: 0.1 }, quantity: 100, unit: 'g', original: '100g Pineapple' },
      { food: { name: 'Berries', calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3 }, quantity: 50, unit: 'g', original: '50g Mixed Berries' },
      { food: { name: 'Almonds', calories: 164, protein: 6, carbs: 6, fat: 14 }, quantity: 15, unit: 'g', original: '15g Sliced Almonds' },
    ],
    instructions: [
      'Place cottage cheese in bowl',
      'Top with pineapple and berries',
      'Sprinkle almonds on top',
      'Drizzle with honey if desired'
    ],
    nutrition: { calories: 280, protein: 20, carbs: 32, fat: 8 },
    source: 'curated',
  },

  {
    id: 'curated_protein_energy_balls',
    name: 'No-Bake Protein Energy Balls',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['high-protein', 'portable', 'meal-prep'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 10,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=400',
    ingredients: [
      { food: { name: 'Rolled Oats', calories: 389, protein: 16.9, carbs: 66, fat: 6.9 }, quantity: 40, unit: 'g', original: '40g Rolled Oats' },
      { food: { name: 'Protein Powder', calories: 120, protein: 24, carbs: 3, fat: 1.5 }, quantity: 20, unit: 'g', original: '20g Protein Powder' },
      { food: { name: 'Peanut Butter', calories: 188, protein: 8, carbs: 6.3, fat: 16 }, quantity: 20, unit: 'g', original: '20g Peanut Butter' },
      { food: { name: 'Honey', calories: 64, protein: 0.1, carbs: 17, fat: 0 }, quantity: 10, unit: 'g', original: '10g Honey' },
      { food: { name: 'Dark Chocolate Chips', calories: 70, protein: 1, carbs: 9, fat: 4 }, quantity: 10, unit: 'g', original: '10g Dark Chocolate Chips' },
    ],
    instructions: [
      'Mix oats, protein powder in bowl',
      'Add peanut butter and honey',
      'Mix until well combined',
      'Fold in chocolate chips',
      'Roll into 4-5 balls and refrigerate'
    ],
    nutrition: { calories: 280, protein: 18, carbs: 35, fat: 10 },
    source: 'curated',
  },

  {
    id: 'curated_hummus_veggies',
    name: 'Hummus & Veggie Plate',
    category: 'Starter',
    area: 'Mediterranean',
    mealType: 'snack',
    tags: ['vegetarian', 'fresh', 'quick'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 5,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1579717173143-a32f0e3d07aa?w=400',
    ingredients: [
      { food: { name: 'Hummus', calories: 166, protein: 7.9, carbs: 14.3, fat: 9.6 }, quantity: 100, unit: 'g', original: '100g Hummus' },
      { food: { name: 'Carrots', calories: 41, protein: 0.9, carbs: 10, fat: 0.2 }, quantity: 100, unit: 'g', original: '100g Carrot Sticks' },
      { food: { name: 'Cucumber', calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1 }, quantity: 100, unit: 'g', original: '100g Cucumber Slices' },
      { food: { name: 'Bell Peppers', calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 }, quantity: 80, unit: 'g', original: '80g Bell Pepper Strips' },
      { food: { name: 'Whole Wheat Pita', calories: 170, protein: 6, carbs: 35, fat: 1.7 }, quantity: 50, unit: 'g', original: '1 small Pita' },
    ],
    instructions: [
      'Place hummus in center of plate',
      'Arrange carrot, cucumber, and pepper around hummus',
      'Cut pita into triangles',
      'Serve fresh'
    ],
    nutrition: { calories: 350, protein: 16, carbs: 62, fat: 8 },
    source: 'curated',
  },

  // POPULAR CHICKEN MEALS
  {
    id: 'curated_chicken_fajitas',
    name: 'Chicken Fajitas',
    category: 'Chicken',
    area: 'Mexican',
    mealType: 'dinner',
    tags: ['high-protein', 'quick', 'popular'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    readyInMinutes: 25,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=400',
    ingredients: [
      { food: { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 180, unit: 'g', original: '180g Chicken Breast' },
      { food: { name: 'Bell Peppers', calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 }, quantity: 150, unit: 'g', original: '1.5 Bell Peppers' },
      { food: { name: 'Onion', calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1 }, quantity: 80, unit: 'g', original: '1 small Onion' },
      { food: { name: 'Flour Tortillas', calories: 150, protein: 4, carbs: 25, fat: 3.5 }, quantity: 80, unit: 'g', original: '2 Tortillas' },
      { food: { name: 'Sour Cream', calories: 60, protein: 1, carbs: 1, fat: 6 }, quantity: 30, unit: 'g', original: '2 tbsp Sour Cream' },
    ],
    instructions: [
      'Slice chicken, peppers, and onions into strips',
      'Season chicken with fajita spices',
      'Sauté chicken in hot pan until cooked',
      'Add peppers and onions, cook until tender',
      'Warm tortillas and fill with chicken mixture',
      'Top with sour cream'
    ],
    nutrition: { calories: 580, protein: 52, carbs: 50, fat: 16 },
    source: 'curated',
  },

  {
    id: 'curated_bbq_chicken',
    name: 'BBQ Chicken with Coleslaw',
    category: 'Chicken',
    area: 'American',
    mealType: 'lunch',
    tags: ['high-protein', 'comfort-food', 'popular'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '20 minutes',
    readyInMinutes: 25,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400',
    ingredients: [
      { food: { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 200, unit: 'g', original: '200g Chicken Breast' },
      { food: { name: 'BBQ Sauce', calories: 70, protein: 0.5, carbs: 17, fat: 0.2 }, quantity: 40, unit: 'g', original: '40g BBQ Sauce' },
      { food: { name: 'Coleslaw', calories: 83, protein: 1.5, carbs: 8, fat: 5 }, quantity: 100, unit: 'g', original: '100g Coleslaw' },
      { food: { name: 'Sweet Potato Fries', calories: 120, protein: 1.5, carbs: 24, fat: 2 }, quantity: 100, unit: 'g', original: '100g Sweet Potato Fries' },
    ],
    instructions: [
      'Season and grill chicken breast',
      'Brush with BBQ sauce during last 5 minutes',
      'Bake sweet potato fries at 425°F for 20 minutes',
      'Serve chicken with coleslaw and fries'
    ],
    nutrition: { calories: 550, protein: 48, carbs: 58, fat: 13 },
    source: 'curated',
  },

  {
    id: 'curated_chicken_caesar_wrap',
    name: 'Chicken Caesar Wrap',
    category: 'Chicken',
    area: 'American',
    mealType: 'lunch',
    tags: ['high-protein', 'portable', 'popular'],
    servings: 1,
    prepTime: '8 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 8,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400',
    ingredients: [
      { food: { name: 'Chicken Breast (grilled)', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 150, unit: 'g', original: '150g Grilled Chicken' },
      { food: { name: 'Whole Wheat Tortilla', calories: 120, protein: 4, carbs: 20, fat: 2.5 }, quantity: 70, unit: 'g', original: '1 Large Tortilla' },
      { food: { name: 'Romaine Lettuce', calories: 17, protein: 1.2, carbs: 3.3, fat: 0.3 }, quantity: 60, unit: 'g', original: '1 cup Romaine' },
      { food: { name: 'Parmesan Cheese', calories: 110, protein: 10, carbs: 1, fat: 7 }, quantity: 20, unit: 'g', original: '20g Parmesan' },
      { food: { name: 'Caesar Dressing (light)', calories: 45, protein: 0.5, carbs: 2, fat: 4 }, quantity: 30, unit: 'ml', original: '2 tbsp Dressing' },
    ],
    instructions: [
      'Slice grilled chicken into strips',
      'Lay tortilla flat and spread dressing',
      'Add lettuce, chicken, and parmesan',
      'Roll tightly and slice in half'
    ],
    nutrition: { calories: 450, protein: 48, carbs: 28, fat: 16 },
    source: 'curated',
  },

  // POPULAR BEEF MEALS
  {
    id: 'curated_beef_tacos',
    name: 'Lean Beef Tacos',
    category: 'Beef',
    area: 'Mexican',
    mealType: 'dinner',
    tags: ['high-protein', 'popular', 'quick'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '10 minutes',
    readyInMinutes: 15,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
    ingredients: [
      { food: { name: 'Lean Ground Beef (93/7)', calories: 176, protein: 21, carbs: 0, fat: 10 }, quantity: 150, unit: 'g', original: '150g Ground Beef' },
      { food: { name: 'Corn Tortillas', calories: 104, protein: 2.7, carbs: 22, fat: 1.1 }, quantity: 60, unit: 'g', original: '3 Corn Tortillas' },
      { food: { name: 'Lettuce', calories: 5, protein: 0.5, carbs: 1, fat: 0 }, quantity: 30, unit: 'g', original: '30g Lettuce' },
      { food: { name: 'Tomato', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 60, unit: 'g', original: '1 small Tomato' },
      { food: { name: 'Cheese', calories: 113, protein: 7, carbs: 0.9, fat: 9.3 }, quantity: 30, unit: 'g', original: '30g Shredded Cheese' },
      { food: { name: 'Salsa', calories: 15, protein: 0.5, carbs: 3, fat: 0 }, quantity: 40, unit: 'ml', original: '40ml Salsa' },
    ],
    instructions: [
      'Brown ground beef with taco seasoning',
      'Warm tortillas',
      'Fill tortillas with beef, lettuce, tomato',
      'Top with cheese and salsa'
    ],
    nutrition: { calories: 520, protein: 42, carbs: 42, fat: 22 },
    source: 'curated',
  },

  {
    id: 'curated_meatballs_marinara',
    name: 'Turkey Meatballs with Marinara',
    category: 'Starter',
    area: 'Italian',
    mealType: 'dinner',
    tags: ['high-protein', 'comfort-food', 'meal-prep'],
    servings: 1,
    prepTime: '15 minutes',
    cookTime: '25 minutes',
    readyInMinutes: 40,
    difficulty: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
    ingredients: [
      { food: { name: 'Ground Turkey (93/7)', calories: 170, protein: 21, carbs: 0, fat: 9 }, quantity: 180, unit: 'g', original: '180g Ground Turkey' },
      { food: { name: 'Whole Wheat Spaghetti', calories: 174, protein: 7.5, carbs: 37, fat: 0.8 }, quantity: 80, unit: 'g', original: '80g Spaghetti' },
      { food: { name: 'Marinara Sauce', calories: 70, protein: 2, carbs: 12, fat: 2 }, quantity: 150, unit: 'ml', original: '150ml Marinara' },
      { food: { name: 'Breadcrumbs', calories: 120, protein: 4, carbs: 22, fat: 1.5 }, quantity: 20, unit: 'g', original: '20g Breadcrumbs' },
      { food: { name: 'Parmesan Cheese', calories: 110, protein: 10, carbs: 1, fat: 7 }, quantity: 15, unit: 'g', original: '15g Parmesan' },
    ],
    instructions: [
      'Mix ground turkey with breadcrumbs, egg, and spices',
      'Form into meatballs',
      'Bake at 400°F for 20 minutes',
      'Cook spaghetti according to package',
      'Heat marinara and add meatballs',
      'Serve over spaghetti with parmesan'
    ],
    nutrition: { calories: 640, protein: 52, carbs: 72, fat: 18 },
    source: 'curated',
  },

  // POPULAR FISH MEALS
  {
    id: 'curated_fish_tacos',
    name: 'Fish Tacos with Lime Crema',
    category: 'Seafood',
    area: 'Mexican',
    mealType: 'lunch',
    tags: ['high-protein', 'fresh', 'popular'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '10 minutes',
    readyInMinutes: 20,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
    ingredients: [
      { food: { name: 'White Fish (cod/tilapia)', calories: 135, protein: 28, carbs: 0, fat: 1.5 }, quantity: 180, unit: 'g', original: '180g White Fish' },
      { food: { name: 'Corn Tortillas', calories: 104, protein: 2.7, carbs: 22, fat: 1.1 }, quantity: 60, unit: 'g', original: '3 Corn Tortillas' },
      { food: { name: 'Cabbage Slaw', calories: 25, protein: 1.3, carbs: 6, fat: 0.1 }, quantity: 80, unit: 'g', original: '80g Cabbage' },
      { food: { name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fat: 0.4 }, quantity: 40, unit: 'g', original: '40g Greek Yogurt' },
      { food: { name: 'Lime Juice', calories: 10, protein: 0.2, carbs: 3.3, fat: 0 }, quantity: 15, unit: 'ml', original: '1 tbsp Lime Juice' },
    ],
    instructions: [
      'Season fish with chili powder and cumin',
      'Grill or pan-fry fish for 4-5 minutes per side',
      'Mix Greek yogurt with lime juice for crema',
      'Warm tortillas',
      'Assemble tacos with fish, slaw, and crema'
    ],
    nutrition: { calories: 400, protein: 48, carbs: 38, fat: 6 },
    source: 'curated',
  },

  {
    id: 'curated_tuna_poke_bowl',
    name: 'Tuna Poke Bowl',
    category: 'Seafood',
    area: 'Japanese',
    mealType: 'lunch',
    tags: ['high-protein', 'fresh', 'bowl'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    readyInMinutes: 25,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    ingredients: [
      { food: { name: 'Sushi-grade Tuna', calories: 144, protein: 32, carbs: 0, fat: 1 }, quantity: 150, unit: 'g', original: '150g Fresh Tuna' },
      { food: { name: 'Sushi Rice', calories: 140, protein: 2.5, carbs: 31, fat: 0.2 }, quantity: 120, unit: 'g', original: '120g Sushi Rice' },
      { food: { name: 'Edamame', calories: 122, protein: 11, carbs: 10, fat: 5 }, quantity: 80, unit: 'g', original: '80g Edamame' },
      { food: { name: 'Cucumber', calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1 }, quantity: 60, unit: 'g', original: '60g Cucumber' },
      { food: { name: 'Avocado', calories: 160, protein: 2, carbs: 8.5, fat: 14.7 }, quantity: 40, unit: 'g', original: '1/4 Avocado' },
      { food: { name: 'Soy Sauce', calories: 11, protein: 1.3, carbs: 1, fat: 0 }, quantity: 15, unit: 'ml', original: '1 tbsp Soy Sauce' },
    ],
    instructions: [
      'Cook sushi rice according to package',
      'Dice tuna into cubes',
      'Marinate tuna in soy sauce for 5 minutes',
      'Assemble bowl: rice, tuna, edamame, cucumber, avocado',
      'Drizzle with remaining marinade'
    ],
    nutrition: { calories: 580, protein: 52, carbs: 56, fat: 18 },
    source: 'curated',
  },

  // POPULAR BREAKFAST
  {
    id: 'curated_breakfast_burrito',
    name: 'Breakfast Burrito',
    category: 'Breakfast',
    area: 'Mexican',
    mealType: 'breakfast',
    tags: ['high-protein', 'portable', 'popular'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '10 minutes',
    readyInMinutes: 15,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400',
    ingredients: [
      { food: { name: 'Eggs', calories: 155, protein: 13, carbs: 1, fat: 11 }, quantity: 150, unit: 'g', original: '3 Eggs' },
      { food: { name: 'Whole Wheat Tortilla', calories: 120, protein: 4, carbs: 20, fat: 2.5 }, quantity: 70, unit: 'g', original: '1 Large Tortilla' },
      { food: { name: 'Black Beans', calories: 132, protein: 8.9, carbs: 24, fat: 0.5 }, quantity: 80, unit: 'g', original: '80g Black Beans' },
      { food: { name: 'Cheese', calories: 113, protein: 7, carbs: 0.9, fat: 9.3 }, quantity: 30, unit: 'g', original: '30g Cheese' },
      { food: { name: 'Salsa', calories: 15, protein: 0.5, carbs: 3, fat: 0 }, quantity: 40, unit: 'ml', original: '40ml Salsa' },
    ],
    instructions: [
      'Scramble eggs in pan',
      'Warm black beans',
      'Lay tortilla flat',
      'Fill with eggs, beans, cheese, and salsa',
      'Roll burrito tightly and serve'
    ],
    nutrition: { calories: 540, protein: 36, carbs: 50, fat: 22 },
    source: 'curated',
  },

  {
    id: 'curated_overnight_oats',
    name: 'Overnight Oats with Berries',
    category: 'Breakfast',
    area: 'American',
    mealType: 'breakfast',
    tags: ['high-protein', 'meal-prep', 'no-cook'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 480,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=400',
    ingredients: [
      { food: { name: 'Rolled Oats', calories: 389, protein: 16.9, carbs: 66, fat: 6.9 }, quantity: 60, unit: 'g', original: '60g Rolled Oats' },
      { food: { name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fat: 0.4 }, quantity: 150, unit: 'g', original: '150g Greek Yogurt' },
      { food: { name: 'Almond Milk', calories: 15, protein: 0.6, carbs: 0.6, fat: 1.1 }, quantity: 100, unit: 'ml', original: '100ml Almond Milk' },
      { food: { name: 'Mixed Berries', calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3 }, quantity: 80, unit: 'g', original: '80g Berries' },
      { food: { name: 'Chia Seeds', calories: 58, protein: 2, carbs: 5, fat: 3.7 }, quantity: 10, unit: 'g', original: '1 tbsp Chia Seeds' },
      { food: { name: 'Honey', calories: 64, protein: 0.1, carbs: 17, fat: 0 }, quantity: 10, unit: 'g', original: '1 tsp Honey' },
    ],
    instructions: [
      'Mix oats, yogurt, almond milk, and chia seeds in jar',
      'Refrigerate overnight (at least 4 hours)',
      'In morning, top with berries and honey',
      'Enjoy cold or microwave briefly'
    ],
    nutrition: { calories: 420, protein: 28, carbs: 62, fat: 10 },
    source: 'curated',
  },

  {
    id: 'curated_french_toast',
    name: 'Protein French Toast',
    category: 'Breakfast',
    area: 'French',
    mealType: 'breakfast',
    tags: ['high-protein', 'sweet', 'popular'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '8 minutes',
    readyInMinutes: 13,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400',
    ingredients: [
      { food: { name: 'Whole Wheat Bread', calories: 247, protein: 13, carbs: 41, fat: 3.4 }, quantity: 60, unit: 'g', original: '2 slices Bread' },
      { food: { name: 'Eggs', calories: 155, protein: 13, carbs: 1, fat: 11 }, quantity: 100, unit: 'g', original: '2 Eggs' },
      { food: { name: 'Protein Powder', calories: 120, protein: 24, carbs: 3, fat: 1.5 }, quantity: 15, unit: 'g', original: '15g Protein Powder' },
      { food: { name: 'Cinnamon', calories: 6, protein: 0.1, carbs: 2, fat: 0 }, quantity: 2, unit: 'g', original: '1 tsp Cinnamon' },
      { food: { name: 'Maple Syrup', calories: 52, protein: 0, carbs: 13, fat: 0 }, quantity: 15, unit: 'ml', original: '1 tbsp Maple Syrup' },
      { food: { name: 'Berries', calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3 }, quantity: 50, unit: 'g', original: '50g Berries' },
    ],
    instructions: [
      'Mix eggs, protein powder, and cinnamon',
      'Dip bread slices in egg mixture',
      'Cook on griddle until golden brown',
      'Top with berries and maple syrup'
    ],
    nutrition: { calories: 480, protein: 46, carbs: 56, fat: 12 },
    source: 'curated',
  },

  // POPULAR SANDWICHES & WRAPS
  {
    id: 'curated_grilled_cheese_tomato',
    name: 'Grilled Cheese & Tomato Soup',
    category: 'Starter',
    area: 'American',
    mealType: 'lunch',
    tags: ['comfort-food', 'popular', 'quick'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '10 minutes',
    readyInMinutes: 15,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400',
    ingredients: [
      { food: { name: 'Whole Wheat Bread', calories: 247, protein: 13, carbs: 41, fat: 3.4 }, quantity: 60, unit: 'g', original: '2 slices Bread' },
      { food: { name: 'Cheddar Cheese', calories: 113, protein: 7, carbs: 0.9, fat: 9.3 }, quantity: 50, unit: 'g', original: '50g Cheddar' },
      { food: { name: 'Tomato Soup', calories: 90, protein: 2, carbs: 17, fat: 2 }, quantity: 250, unit: 'ml', original: '1 cup Tomato Soup' },
      { food: { name: 'Butter', calories: 102, protein: 0.1, carbs: 0, fat: 11.5 }, quantity: 10, unit: 'g', original: '10g Butter' },
    ],
    instructions: [
      'Butter one side of each bread slice',
      'Place cheese between slices (butter side out)',
      'Grill in pan until golden and cheese melts',
      'Heat tomato soup',
      'Serve together'
    ],
    nutrition: { calories: 480, protein: 22, carbs: 56, fat: 20 },
    source: 'curated',
  },

  {
    id: 'curated_club_sandwich',
    name: 'Turkey Club Sandwich',
    category: 'Starter',
    area: 'American',
    mealType: 'lunch',
    tags: ['high-protein', 'popular', 'filling'],
    servings: 1,
    prepTime: '8 minutes',
    cookTime: '2 minutes',
    readyInMinutes: 10,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400',
    ingredients: [
      { food: { name: 'Whole Wheat Bread', calories: 247, protein: 13, carbs: 41, fat: 3.4 }, quantity: 90, unit: 'g', original: '3 slices Bread' },
      { food: { name: 'Turkey Breast', calories: 104, protein: 24, carbs: 0, fat: 0.7 }, quantity: 100, unit: 'g', original: '100g Turkey' },
      { food: { name: 'Bacon', calories: 43, protein: 3, carbs: 0.1, fat: 3.3 }, quantity: 20, unit: 'g', original: '2 strips Bacon' },
      { food: { name: 'Lettuce', calories: 5, protein: 0.5, carbs: 1, fat: 0 }, quantity: 20, unit: 'g', original: '2 leaves Lettuce' },
      { food: { name: 'Tomato', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 60, unit: 'g', original: '3 slices Tomato' },
      { food: { name: 'Mayo (light)', calories: 35, protein: 0, carbs: 1, fat: 3.5 }, quantity: 15, unit: 'g', original: '1 tbsp Mayo' },
    ],
    instructions: [
      'Toast bread slices',
      'Cook bacon until crispy',
      'Spread mayo on bread',
      'Layer: bread, turkey, lettuce, tomato, bread, bacon, bread',
      'Secure with toothpicks and cut into quarters'
    ],
    nutrition: { calories: 520, protein: 48, carbs: 50, fat: 14 },
    source: 'curated',
  },

  {
    id: 'curated_blt_sandwich',
    name: 'BLT Sandwich',
    category: 'Starter',
    area: 'American',
    mealType: 'lunch',
    tags: ['popular', 'classic', 'quick'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '8 minutes',
    readyInMinutes: 13,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=400',
    ingredients: [
      { food: { name: 'Whole Wheat Bread', calories: 247, protein: 13, carbs: 41, fat: 3.4 }, quantity: 60, unit: 'g', original: '2 slices Bread' },
      { food: { name: 'Bacon', calories: 43, protein: 3, carbs: 0.1, fat: 3.3 }, quantity: 40, unit: 'g', original: '4 strips Bacon' },
      { food: { name: 'Lettuce', calories: 5, protein: 0.5, carbs: 1, fat: 0 }, quantity: 30, unit: 'g', original: '3 leaves Lettuce' },
      { food: { name: 'Tomato', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 80, unit: 'g', original: '4 slices Tomato' },
      { food: { name: 'Mayo', calories: 94, protein: 0.1, carbs: 0.1, fat: 10 }, quantity: 15, unit: 'g', original: '1 tbsp Mayo' },
    ],
    instructions: [
      'Cook bacon until crispy',
      'Toast bread',
      'Spread mayo on bread',
      'Layer bacon, lettuce, and tomato',
      'Top with second slice and cut diagonally'
    ],
    nutrition: { calories: 420, protein: 20, carbs: 48, fat: 18 },
    source: 'curated',
  },

  // POPULAR VEGETARIAN
  {
    id: 'curated_veggie_burger',
    name: 'Black Bean Veggie Burger',
    category: 'Vegetarian',
    area: 'American',
    mealType: 'lunch',
    tags: ['vegetarian', 'popular', 'filling'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '12 minutes',
    readyInMinutes: 22,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400',
    ingredients: [
      { food: { name: 'Black Bean Patty', calories: 150, protein: 10, carbs: 22, fat: 3 }, quantity: 120, unit: 'g', original: '1 Black Bean Patty' },
      { food: { name: 'Whole Wheat Bun', calories: 170, protein: 6, carbs: 30, fat: 3 }, quantity: 60, unit: 'g', original: '1 Burger Bun' },
      { food: { name: 'Avocado', calories: 160, protein: 2, carbs: 8.5, fat: 14.7 }, quantity: 40, unit: 'g', original: '1/4 Avocado' },
      { food: { name: 'Lettuce', calories: 5, protein: 0.5, carbs: 1, fat: 0 }, quantity: 20, unit: 'g', original: 'Lettuce leaf' },
      { food: { name: 'Tomato', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 40, unit: 'g', original: '2 slices Tomato' },
      { food: { name: 'Sweet Potato Fries', calories: 120, protein: 1.5, carbs: 24, fat: 2 }, quantity: 100, unit: 'g', original: '100g Fries' },
    ],
    instructions: [
      'Cook black bean patty according to package',
      'Toast burger bun',
      'Bake sweet potato fries at 425°F',
      'Assemble burger with patty, avocado, lettuce, tomato',
      'Serve with fries'
    ],
    nutrition: { calories: 580, protein: 22, carbs: 88, fat: 20 },
    source: 'curated',
  },

  {
    id: 'curated_caprese_sandwich',
    name: 'Caprese Sandwich',
    category: 'Vegetarian',
    area: 'Italian',
    mealType: 'lunch',
    tags: ['vegetarian', 'fresh', 'quick'],
    servings: 1,
    prepTime: '5 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 5,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400',
    ingredients: [
      { food: { name: 'Ciabatta Bread', calories: 140, protein: 4.5, carbs: 26, fat: 1.5 }, quantity: 80, unit: 'g', original: '1 small Ciabatta' },
      { food: { name: 'Fresh Mozzarella', calories: 280, protein: 19, carbs: 3, fat: 21 }, quantity: 80, unit: 'g', original: '80g Mozzarella' },
      { food: { name: 'Tomato', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 100, unit: 'g', original: '1 large Tomato' },
      { food: { name: 'Fresh Basil', calories: 1, protein: 0.1, carbs: 0.2, fat: 0 }, quantity: 5, unit: 'g', original: '5 leaves Basil' },
      { food: { name: 'Balsamic Glaze', calories: 20, protein: 0, carbs: 5, fat: 0 }, quantity: 10, unit: 'ml', original: '1 tbsp Balsamic' },
      { food: { name: 'Olive Oil', calories: 119, protein: 0, carbs: 0, fat: 13.5 }, quantity: 5, unit: 'ml', original: '1 tsp Olive Oil' },
    ],
    instructions: [
      'Slice ciabatta in half horizontally',
      'Drizzle olive oil on both sides',
      'Layer mozzarella, tomato slices, and basil',
      'Drizzle with balsamic glaze',
      'Close sandwich and serve'
    ],
    nutrition: { calories: 520, protein: 26, carbs: 42, fat: 30 },
    source: 'curated',
  },

  // POPULAR BOWLS
  {
    id: 'curated_teriyaki_chicken_bowl',
    name: 'Teriyaki Chicken Bowl',
    category: 'Chicken',
    area: 'Japanese',
    mealType: 'dinner',
    tags: ['high-protein', 'bowl', 'popular'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    readyInMinutes: 30,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    ingredients: [
      { food: { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6 }, quantity: 180, unit: 'g', original: '180g Chicken Breast' },
      { food: { name: 'White Rice', calories: 130, protein: 2.4, carbs: 28, fat: 0.3 }, quantity: 150, unit: 'g', original: '150g White Rice' },
      { food: { name: 'Broccoli', calories: 34, protein: 2.8, carbs: 7, fat: 0.4 }, quantity: 100, unit: 'g', original: '100g Broccoli' },
      { food: { name: 'Teriyaki Sauce', calories: 60, protein: 1, carbs: 13, fat: 0 }, quantity: 40, unit: 'ml', original: '40ml Teriyaki Sauce' },
      { food: { name: 'Sesame Seeds', calories: 52, protein: 1.6, carbs: 2.1, fat: 4.5 }, quantity: 5, unit: 'g', original: '1 tsp Sesame Seeds' },
    ],
    instructions: [
      'Cook rice according to package',
      'Dice chicken and cook in pan',
      'Steam broccoli',
      'Add teriyaki sauce to chicken in last 2 minutes',
      'Assemble bowl with rice, chicken, and broccoli',
      'Garnish with sesame seeds'
    ],
    nutrition: { calories: 580, protein: 52, carbs: 62, fat: 10 },
    source: 'curated',
  },

  {
    id: 'curated_mediterranean_bowl',
    name: 'Mediterranean Bowl',
    category: 'Vegetarian',
    area: 'Mediterranean',
    mealType: 'lunch',
    tags: ['vegetarian', 'fresh', 'bowl'],
    servings: 1,
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    readyInMinutes: 25,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    ingredients: [
      { food: { name: 'Brown Rice', calories: 111, protein: 2.6, carbs: 23, fat: 0.9 }, quantity: 150, unit: 'g', original: '150g Brown Rice' },
      { food: { name: 'Chickpeas', calories: 164, protein: 8.9, carbs: 27, fat: 2.6 }, quantity: 120, unit: 'g', original: '120g Chickpeas' },
      { food: { name: 'Cucumber', calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1 }, quantity: 80, unit: 'g', original: '80g Cucumber' },
      { food: { name: 'Tomato', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 }, quantity: 80, unit: 'g', original: '80g Tomato' },
      { food: { name: 'Feta Cheese', calories: 264, protein: 14, carbs: 4, fat: 21 }, quantity: 40, unit: 'g', original: '40g Feta' },
      { food: { name: 'Hummus', calories: 166, protein: 7.9, carbs: 14.3, fat: 9.6 }, quantity: 50, unit: 'g', original: '50g Hummus' },
    ],
    instructions: [
      'Cook brown rice',
      'Roast chickpeas with olive oil and spices at 400°F for 20 minutes',
      'Dice cucumber and tomato',
      'Assemble bowl: rice, chickpeas, veggies, feta',
      'Add dollop of hummus'
    ],
    nutrition: { calories: 600, protein: 28, carbs: 76, fat: 22 },
    source: 'curated',
  },

  // MORE POPULAR SNACKS
  {
    id: 'curated_apple_peanut_butter',
    name: 'Apple Slices with Peanut Butter',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['quick', 'portable', 'popular'],
    featured: true, // MOST POPULAR - Simple, popular snack
    servings: 1,
    prepTime: '2 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 2,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400',
    ingredients: [
      { food: { name: 'Apple', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 }, quantity: 180, unit: 'g', original: '1 medium Apple' },
      { food: { name: 'Peanut Butter', calories: 188, protein: 8, carbs: 6.3, fat: 16 }, quantity: 30, unit: 'g', original: '2 tbsp Peanut Butter' },
    ],
    instructions: [
      'Slice apple into wedges',
      'Serve with peanut butter for dipping'
    ],
    nutrition: { calories: 280, protein: 8, carbs: 32, fat: 16 },
    source: 'curated',
  },

  {
    id: 'curated_trail_mix',
    name: 'Trail Mix',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['portable', 'energy', 'popular'],
    servings: 1,
    prepTime: '2 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 2,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1599909533879-4314c38d8d17?w=400',
    ingredients: [
      { food: { name: 'Almonds', calories: 164, protein: 6, carbs: 6, fat: 14 }, quantity: 30, unit: 'g', original: '30g Almonds' },
      { food: { name: 'Cashews', calories: 157, protein: 5.2, carbs: 8.6, fat: 12.4 }, quantity: 20, unit: 'g', original: '20g Cashews' },
      { food: { name: 'Dried Cranberries', calories: 92, protein: 0.1, carbs: 25, fat: 0.1 }, quantity: 20, unit: 'g', original: '20g Cranberries' },
      { food: { name: 'Dark Chocolate Chips', calories: 70, protein: 1, carbs: 9, fat: 4 }, quantity: 15, unit: 'g', original: '15g Chocolate Chips' },
    ],
    instructions: [
      'Mix all ingredients in container',
      'Shake to combine',
      'Portion into snack bags'
    ],
    nutrition: { calories: 320, protein: 10, carbs: 42, fat: 16 },
    source: 'curated',
  },

  {
    id: 'curated_greek_yogurt_parfait',
    name: 'Greek Yogurt Parfait',
    category: 'Starter',
    area: 'Greek',
    mealType: 'snack',
    tags: ['high-protein', 'sweet', 'popular'],
    featured: true, // MOST POPULAR - Popular breakfast/snack
    servings: 1,
    prepTime: '3 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 3,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    ingredients: [
      { food: { name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fat: 0.4 }, quantity: 200, unit: 'g', original: '200g Greek Yogurt' },
      { food: { name: 'Granola', calories: 150, protein: 3, carbs: 23, fat: 6 }, quantity: 40, unit: 'g', original: '40g Granola' },
      { food: { name: 'Mixed Berries', calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3 }, quantity: 80, unit: 'g', original: '80g Berries' },
      { food: { name: 'Honey', calories: 64, protein: 0.1, carbs: 17, fat: 0 }, quantity: 10, unit: 'g', original: '1 tsp Honey' },
    ],
    instructions: [
      'Layer half the yogurt in glass or bowl',
      'Add half the granola and berries',
      'Repeat layers',
      'Drizzle honey on top'
    ],
    nutrition: { calories: 300, protein: 14, carbs: 50, fat: 6 },
    source: 'curated',
  },

  {
    id: 'curated_rice_cakes',
    name: 'Rice Cakes with Almond Butter & Banana',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['quick', 'portable', 'energizing'],
    servings: 1,
    prepTime: '3 minutes',
    cookTime: '0 minutes',
    readyInMinutes: 3,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400',
    ingredients: [
      { food: { name: 'Rice Cakes', calories: 70, protein: 1.5, carbs: 15, fat: 0.5 }, quantity: 18, unit: 'g', original: '2 Rice Cakes' },
      { food: { name: 'Almond Butter', calories: 98, protein: 3.4, carbs: 3, fat: 9 }, quantity: 20, unit: 'g', original: '20g Almond Butter' },
      { food: { name: 'Banana', calories: 89, protein: 1.1, carbs: 23, fat: 0.3 }, quantity: 80, unit: 'g', original: '1/2 Banana' },
      { food: { name: 'Cinnamon', calories: 6, protein: 0.1, carbs: 2, fat: 0 }, quantity: 1, unit: 'g', original: 'Sprinkle Cinnamon' },
    ],
    instructions: [
      'Spread almond butter on rice cakes',
      'Slice banana and place on top',
      'Sprinkle with cinnamon'
    ],
    nutrition: { calories: 260, protein: 6, carbs: 42, fat: 10 },
    source: 'curated',
  },

  {
    id: 'curated_hard_boiled_eggs',
    name: 'Hard Boiled Eggs with Everything Seasoning',
    category: 'Starter',
    area: 'American',
    mealType: 'snack',
    tags: ['high-protein', 'portable', 'meal-prep'],
    servings: 1,
    prepTime: '0 minutes',
    cookTime: '12 minutes',
    readyInMinutes: 12,
    difficulty: 'easy',
    imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400',
    ingredients: [
      { food: { name: 'Eggs', calories: 155, protein: 13, carbs: 1, fat: 11 }, quantity: 150, unit: 'g', original: '3 Large Eggs' },
      { food: { name: 'Everything Bagel Seasoning', calories: 5, protein: 0.2, carbs: 1, fat: 0.2 }, quantity: 2, unit: 'g', original: '1/2 tsp Seasoning' },
    ],
    instructions: [
      'Place eggs in pot, cover with water',
      'Bring to boil, then turn off heat',
      'Cover and let sit for 10-12 minutes',
      'Transfer to ice bath',
      'Peel and sprinkle with everything seasoning'
    ],
    nutrition: { calories: 160, protein: 13, carbs: 2, fat: 11 },
    source: 'curated',
  },
];
