// Default foods to populate the database with common items
export const defaultFoods = [
  // Proteins
  {
    name: "White Tuna (in water)",
    brand: "Generic",
    barcode: null,
    calories: 128,
    protein: 29.9,
    carbs: 0,
    fat: 0.9,
    fiber: 0,
    sugar: 0,
    sodium: 0.377,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Cheddar Cheese",
    brand: "Generic",
    barcode: null,
    calories: 402,
    protein: 24.9,
    carbs: 1.3,
    fat: 33.1,
    fiber: 0,
    sugar: 0.5,
    sodium: 0.621,
    saturated_fat: 21,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Chicken Breast (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 0.074,
    saturated_fat: 1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Eggs (large)",
    brand: "Generic",
    barcode: null,
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 0.124,
    saturated_fat: 3.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Salmon (Atlantic)",
    brand: "Generic",
    barcode: null,
    calories: 208,
    protein: 20.4,
    carbs: 0,
    fat: 13.4,
    fiber: 0,
    sugar: 0,
    sodium: 0.059,
    saturated_fat: 3.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Greek Yogurt (plain)",
    brand: "Generic",
    barcode: null,
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.2,
    sodium: 0.036,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },

  // Carbohydrates
  {
    name: "White Rice (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Brown Rice (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 112,
    protein: 2.3,
    carbs: 23.5,
    fat: 0.8,
    fiber: 1.8,
    sugar: 0.2,
    sodium: 0.004,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Pasta (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 2.5,
    sugar: 0.8,
    sodium: 0.001,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Oatmeal (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 68,
    protein: 2.4,
    carbs: 12,
    fat: 1.4,
    fiber: 1.7,
    sugar: 0.3,
    sodium: 0.049,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Sweet Potato (baked)",
    brand: "Generic",
    barcode: null,
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 0.055,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Quinoa (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 0.007,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },

  // Fruits
  {
    name: "Apple",
    brand: "Generic",
    barcode: null,
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10.4,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Banana",
    brand: "Generic",
    barcode: null,
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Orange",
    brand: "Generic",
    barcode: null,
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9.4,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Strawberries",
    brand: "Generic",
    barcode: null,
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Blueberries",
    brand: "Generic",
    barcode: null,
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },

  // Vegetables
  {
    name: "Broccoli (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 35,
    protein: 2.4,
    carbs: 7.2,
    fat: 0.4,
    fiber: 3.3,
    sugar: 1.4,
    sodium: 0.041,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Spinach (raw)",
    brand: "Generic",
    barcode: null,
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 0.079,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Carrots (raw)",
    brand: "Generic",
    barcode: null,
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 0.069,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Tomato",
    brand: "Generic",
    barcode: null,
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 0.005,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Cucumber",
    brand: "Generic",
    barcode: null,
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 0.002,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Bell Pepper (red)",
    brand: "Generic",
    barcode: null,
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    sugar: 4.2,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },

  // Dairy & Alternatives
  {
    name: "Whole Milk",
    brand: "Generic",
    barcode: null,
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 5,
    sodium: 0.043,
    saturated_fat: 1.9,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Almond Milk (unsweetened)",
    brand: "Generic",
    barcode: null,
    calories: 17,
    protein: 0.6,
    carbs: 0.6,
    fat: 1.5,
    fiber: 0.2,
    sugar: 0.1,
    sodium: 0.072,
    saturated_fat: 0.1,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Cottage Cheese",
    brand: "Generic",
    barcode: null,
    calories: 98,
    protein: 11.1,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    sodium: 0.364,
    saturated_fat: 1.7,
    serving_size: "100g",
    source: "default"
  },

  // Nuts & Seeds
  {
    name: "Almonds",
    brand: "Generic",
    barcode: null,
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 0.001,
    saturated_fat: 3.8,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Peanut Butter",
    brand: "Generic",
    barcode: null,
    calories: 588,
    protein: 25.1,
    carbs: 20,
    fat: 50.4,
    fiber: 6.3,
    sugar: 9.2,
    sodium: 0.017,
    saturated_fat: 10.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Walnuts",
    brand: "Generic",
    barcode: null,
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 0.002,
    saturated_fat: 6.1,
    serving_size: "100g",
    source: "default"
  },

  // Common Foods
  {
    name: "Bread (whole wheat)",
    brand: "Generic",
    barcode: null,
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 6.8,
    sugar: 6,
    sodium: 0.4,
    saturated_fat: 0.7,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Olive Oil",
    brand: "Generic",
    barcode: null,
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0.002,
    saturated_fat: 13.8,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Honey",
    brand: "Generic",
    barcode: null,
    calories: 304,
    protein: 0.3,
    carbs: 82.4,
    fat: 0,
    fiber: 0.2,
    sugar: 82.1,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Avocado",
    brand: "Generic",
    barcode: null,
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 0.007,
    saturated_fat: 2.1,
    serving_size: "100g",
    source: "default"
  }
];