// Default foods to populate the database with common items
export const defaultFoods = [
  // Proteins - Beef
  {
    name: "Ground Beef (80/20 cooked)",
    brand: "Generic",
    barcode: null,
    calories: 254,
    protein: 26,
    carbs: 0,
    fat: 17,
    fiber: 0,
    sugar: 0,
    sodium: 0.072,
    saturated_fat: 6.8,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Ground Beef (90/10 cooked)",
    brand: "Generic",
    barcode: null,
    calories: 212,
    protein: 28.9,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sugar: 0,
    sodium: 0.071,
    saturated_fat: 4,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Beef Steak (sirloin)",
    brand: "Generic",
    barcode: null,
    calories: 271,
    protein: 26,
    carbs: 0,
    fat: 18,
    fiber: 0,
    sugar: 0,
    sodium: 0.055,
    saturated_fat: 7,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Beef Steak (ribeye)",
    brand: "Generic",
    barcode: null,
    calories: 291,
    protein: 24,
    carbs: 0,
    fat: 21,
    fiber: 0,
    sugar: 0,
    sodium: 0.058,
    saturated_fat: 9,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Roast Beef",
    brand: "Generic",
    barcode: null,
    calories: 239,
    protein: 27.3,
    carbs: 0,
    fat: 13.6,
    fiber: 0,
    sugar: 0,
    sodium: 0.054,
    saturated_fat: 5.2,
    serving_size: "100g",
    source: "default"
  },

  // Proteins - Other Meats
  {
    name: "Pork Chops (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 231,
    protein: 23.9,
    carbs: 0,
    fat: 14.3,
    fiber: 0,
    sugar: 0,
    sodium: 0.062,
    saturated_fat: 5.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Bacon (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    fiber: 0,
    sugar: 0,
    sodium: 2.31,
    saturated_fat: 13.7,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Ham (sliced)",
    brand: "Generic",
    barcode: null,
    calories: 145,
    protein: 21,
    carbs: 1.5,
    fat: 6,
    fiber: 0,
    sugar: 1.2,
    sodium: 1.5,
    saturated_fat: 2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Turkey Breast (deli sliced)",
    brand: "Generic",
    barcode: null,
    calories: 104,
    protein: 24,
    carbs: 1.2,
    fat: 0.5,
    fiber: 0,
    sugar: 1,
    sodium: 1.04,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Ground Turkey (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 203,
    protein: 27,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sugar: 0,
    sodium: 0.087,
    saturated_fat: 2.6,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Lamb Chops (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 294,
    protein: 25.5,
    carbs: 0,
    fat: 20.8,
    fiber: 0,
    sugar: 0,
    sodium: 0.072,
    saturated_fat: 8.8,
    serving_size: "100g",
    source: "default"
  },

  // Proteins - Fish & Seafood
  {
    name: "White Tuna (in water)",
    brand: "Generic",
    barcode: null,
    calories: 128,
    protein: 29.9,
    carbs: 0,
    fat: 0.9,
    fiber: 0,
    sugar: 0,
    sodium: 0.377,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Shrimp (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    sugar: 0,
    sodium: 0.111,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Tilapia (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 128,
    protein: 26.1,
    carbs: 0,
    fat: 2.7,
    fiber: 0,
    sugar: 0,
    sodium: 0.056,
    saturated_fat: 0.9,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Cod (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 105,
    protein: 23,
    carbs: 0,
    fat: 0.9,
    fiber: 0,
    sugar: 0,
    sodium: 0.078,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Cheddar Cheese",
    brand: "Generic",
    barcode: null,
    calories: 402,
    protein: 24.9,
    carbs: 1.3,
    fat: 33.1,
    fiber: 0,
    sugar: 0.5,
    sodium: 0.621,
    saturated_fat: 21,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Chicken Breast (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 0.074,
    saturated_fat: 1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Eggs (large)",
    brand: "Generic",
    barcode: null,
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 0.124,
    saturated_fat: 3.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Salmon (Atlantic)",
    brand: "Generic",
    barcode: null,
    calories: 208,
    protein: 20.4,
    carbs: 0,
    fat: 13.4,
    fiber: 0,
    sugar: 0,
    sodium: 0.059,
    saturated_fat: 3.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Greek Yogurt (plain)",
    brand: "Generic",
    barcode: null,
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.2,
    sodium: 0.036,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },

  // Carbohydrates
  {
    name: "White Rice (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Brown Rice (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 112,
    protein: 2.3,
    carbs: 23.5,
    fat: 0.8,
    fiber: 1.8,
    sugar: 0.2,
    sodium: 0.004,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Pasta (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 2.5,
    sugar: 0.8,
    sodium: 0.001,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Oatmeal (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 68,
    protein: 2.4,
    carbs: 12,
    fat: 1.4,
    fiber: 1.7,
    sugar: 0.3,
    sodium: 0.049,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Sweet Potato (baked)",
    brand: "Generic",
    barcode: null,
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 0.055,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Quinoa (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 0.007,
    saturated_fat: 0.2,
    serving_size: "100g",
    source: "default"
  },

  // Fruits
  {
    name: "Apple",
    brand: "Generic",
    barcode: null,
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10.4,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Banana",
    brand: "Generic",
    barcode: null,
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Orange",
    brand: "Generic",
    barcode: null,
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9.4,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Strawberries",
    brand: "Generic",
    barcode: null,
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Blueberries",
    brand: "Generic",
    barcode: null,
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Grapes (red/green)",
    brand: "Generic",
    barcode: null,
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    sugar: 15.5,
    sodium: 0.002,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Watermelon",
    brand: "Generic",
    barcode: null,
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    sugar: 6.2,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Pineapple",
    brand: "Generic",
    barcode: null,
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    sugar: 9.9,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Mango",
    brand: "Generic",
    barcode: null,
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    sugar: 13.7,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Peach",
    brand: "Generic",
    barcode: null,
    calories: 39,
    protein: 0.9,
    carbs: 9.5,
    fat: 0.3,
    fiber: 1.5,
    sugar: 8.4,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Pear",
    brand: "Generic",
    barcode: null,
    calories: 57,
    protein: 0.4,
    carbs: 15.2,
    fat: 0.1,
    fiber: 3.1,
    sugar: 9.8,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Kiwi",
    brand: "Generic",
    barcode: null,
    calories: 61,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
    fiber: 3,
    sugar: 9,
    sodium: 0.003,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Raspberries",
    brand: "Generic",
    barcode: null,
    calories: 52,
    protein: 1.2,
    carbs: 11.9,
    fat: 0.7,
    fiber: 6.5,
    sugar: 4.4,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Blackberries",
    brand: "Generic",
    barcode: null,
    calories: 43,
    protein: 1.4,
    carbs: 9.6,
    fat: 0.5,
    fiber: 5.3,
    sugar: 4.9,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Cherries",
    brand: "Generic",
    barcode: null,
    calories: 63,
    protein: 1.1,
    carbs: 16,
    fat: 0.2,
    fiber: 2.1,
    sugar: 12.8,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Plum",
    brand: "Generic",
    barcode: null,
    calories: 46,
    protein: 0.7,
    carbs: 11.4,
    fat: 0.3,
    fiber: 1.4,
    sugar: 9.9,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Cantaloupe",
    brand: "Generic",
    barcode: null,
    calories: 34,
    protein: 0.8,
    carbs: 8.2,
    fat: 0.2,
    fiber: 0.9,
    sugar: 7.9,
    sodium: 0.016,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Grapefruit",
    brand: "Generic",
    barcode: null,
    calories: 42,
    protein: 0.8,
    carbs: 10.7,
    fat: 0.1,
    fiber: 1.6,
    sugar: 6.9,
    sodium: 0,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },

  // Vegetables
  {
    name: "Broccoli (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 35,
    protein: 2.4,
    carbs: 7.2,
    fat: 0.4,
    fiber: 3.3,
    sugar: 1.4,
    sodium: 0.041,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Spinach (raw)",
    brand: "Generic",
    barcode: null,
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 0.079,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Carrots (raw)",
    brand: "Generic",
    barcode: null,
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 0.069,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Tomato",
    brand: "Generic",
    barcode: null,
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 0.005,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Cucumber",
    brand: "Generic",
    barcode: null,
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 0.002,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Bell Pepper (red)",
    brand: "Generic",
    barcode: null,
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    sugar: 4.2,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },

  // Dairy & Alternatives
  {
    name: "Whole Milk",
    brand: "Generic",
    barcode: null,
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 5,
    sodium: 0.043,
    saturated_fat: 1.9,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Almond Milk (unsweetened)",
    brand: "Generic",
    barcode: null,
    calories: 17,
    protein: 0.6,
    carbs: 0.6,
    fat: 1.5,
    fiber: 0.2,
    sugar: 0.1,
    sodium: 0.072,
    saturated_fat: 0.1,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Cottage Cheese",
    brand: "Generic",
    barcode: null,
    calories: 98,
    protein: 11.1,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    sodium: 0.364,
    saturated_fat: 1.7,
    serving_size: "100g",
    source: "default"
  },

  // Nuts & Seeds
  {
    name: "Almonds",
    brand: "Generic",
    barcode: null,
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 0.001,
    saturated_fat: 3.8,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Peanut Butter",
    brand: "Generic",
    barcode: null,
    calories: 588,
    protein: 25.1,
    carbs: 20,
    fat: 50.4,
    fiber: 6.3,
    sugar: 9.2,
    sodium: 0.017,
    saturated_fat: 10.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Walnuts",
    brand: "Generic",
    barcode: null,
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 0.002,
    saturated_fat: 6.1,
    serving_size: "100g",
    source: "default"
  },

  // Common Foods
  {
    name: "Bread (whole wheat)",
    brand: "Generic",
    barcode: null,
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 6.8,
    sugar: 6,
    sodium: 0.4,
    saturated_fat: 0.7,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Olive Oil",
    brand: "Generic",
    barcode: null,
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0.002,
    saturated_fat: 13.8,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Honey",
    brand: "Generic",
    barcode: null,
    calories: 304,
    protein: 0.3,
    carbs: 82.4,
    fat: 0,
    fiber: 0.2,
    sugar: 82.1,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Avocado",
    brand: "Generic",
    barcode: null,
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 0.007,
    saturated_fat: 2.1,
    serving_size: "100g",
    source: "default"
  },

  // Common Prepared Foods
  {
    name: "Pizza (cheese)",
    brand: "Generic",
    barcode: null,
    calories: 266,
    protein: 11,
    carbs: 33,
    fat: 10,
    fiber: 2.3,
    sugar: 3.6,
    sodium: 0.598,
    saturated_fat: 4.8,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Burger (beef with bun)",
    brand: "Generic",
    barcode: null,
    calories: 295,
    protein: 17,
    carbs: 24,
    fat: 14,
    fiber: 1.1,
    sugar: 4.7,
    sodium: 0.414,
    saturated_fat: 5.5,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "French Fries",
    brand: "Generic",
    barcode: null,
    calories: 312,
    protein: 3.4,
    carbs: 41,
    fat: 15,
    fiber: 3.8,
    sugar: 0.3,
    sodium: 0.21,
    saturated_fat: 2.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Sushi Roll (California)",
    brand: "Generic",
    barcode: null,
    calories: 255,
    protein: 9,
    carbs: 38,
    fat: 7,
    fiber: 1.5,
    sugar: 6,
    sodium: 0.328,
    saturated_fat: 1.6,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Burrito (bean and cheese)",
    brand: "Generic",
    barcode: null,
    calories: 206,
    protein: 7.9,
    carbs: 26.5,
    fat: 7.3,
    fiber: 3.8,
    sugar: 1.5,
    sodium: 0.428,
    saturated_fat: 3.6,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Caesar Salad (with dressing)",
    brand: "Generic",
    barcode: null,
    calories: 158,
    protein: 8.5,
    carbs: 7,
    fat: 12,
    fiber: 1.8,
    sugar: 2.1,
    sodium: 0.365,
    saturated_fat: 3.2,
    serving_size: "100g",
    source: "default"
  },

  // Snacks and Treats
  {
    name: "Potato Chips",
    brand: "Generic",
    barcode: null,
    calories: 536,
    protein: 7,
    carbs: 53,
    fat: 35,
    fiber: 3.4,
    sugar: 0.3,
    sodium: 0.6,
    saturated_fat: 3.5,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Chocolate (dark 70%)",
    brand: "Generic",
    barcode: null,
    calories: 598,
    protein: 7.8,
    carbs: 45.9,
    fat: 42.6,
    fiber: 10.9,
    sugar: 24,
    sodium: 0.02,
    saturated_fat: 24.5,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Ice Cream (vanilla)",
    brand: "Generic",
    barcode: null,
    calories: 207,
    protein: 3.5,
    carbs: 24,
    fat: 11,
    fiber: 0.5,
    sugar: 21,
    sodium: 0.08,
    saturated_fat: 7,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Protein Bar",
    brand: "Generic",
    barcode: null,
    calories: 380,
    protein: 20,
    carbs: 42,
    fat: 13,
    fiber: 3,
    sugar: 22,
    sodium: 0.25,
    saturated_fat: 6,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Granola",
    brand: "Generic",
    barcode: null,
    calories: 471,
    protein: 10,
    carbs: 64,
    fat: 20,
    fiber: 7,
    sugar: 24,
    sodium: 0.026,
    saturated_fat: 4,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Popcorn (air-popped)",
    brand: "Generic",
    barcode: null,
    calories: 387,
    protein: 12.9,
    carbs: 77.8,
    fat: 4.5,
    fiber: 14.5,
    sugar: 0.9,
    sodium: 0.008,
    saturated_fat: 0.6,
    serving_size: "100g",
    source: "default"
  },

  // Beverages (per 100ml)
  {
    name: "Orange Juice",
    brand: "Generic",
    barcode: null,
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    sugar: 8.4,
    sodium: 0.001,
    saturated_fat: 0,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Coca Cola",
    brand: "Coca-Cola",
    barcode: null,
    calories: 42,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    fiber: 0,
    sugar: 10.6,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Protein Shake (whey)",
    brand: "Generic",
    barcode: null,
    calories: 51,
    protein: 8.5,
    carbs: 2,
    fat: 1,
    fiber: 0,
    sugar: 1.5,
    sodium: 0.05,
    saturated_fat: 0.6,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Beer",
    brand: "Generic",
    barcode: null,
    calories: 43,
    protein: 0.5,
    carbs: 3.6,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Red Wine",
    brand: "Generic",
    barcode: null,
    calories: 85,
    protein: 0.1,
    carbs: 2.6,
    fat: 0,
    fiber: 0,
    sugar: 0.6,
    sodium: 0.004,
    saturated_fat: 0,
    serving_size: "100ml",
    source: "default"
  },

  // Plant-based Proteins
  {
    name: "Tofu (firm)",
    brand: "Generic",
    barcode: null,
    calories: 144,
    protein: 17.3,
    carbs: 2.8,
    fat: 8.7,
    fiber: 2.3,
    sugar: 0.6,
    sodium: 0.012,
    saturated_fat: 1.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Black Beans (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    sugar: 0.3,
    sodium: 0.001,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Chickpeas (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    sodium: 0.007,
    saturated_fat: 0.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Lentils (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 116,
    protein: 9,
    carbs: 20.1,
    fat: 0.4,
    fiber: 7.9,
    sugar: 1.8,
    sodium: 0.002,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Edamame (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 121,
    protein: 11.9,
    carbs: 8.9,
    fat: 5.2,
    fiber: 5.2,
    sugar: 2.2,
    sodium: 0.005,
    saturated_fat: 0.6,
    serving_size: "100g",
    source: "default"
  },

  // More Grains
  {
    name: "Bagel (plain)",
    brand: "Generic",
    barcode: null,
    calories: 257,
    protein: 10,
    carbs: 50,
    fat: 1.6,
    fiber: 2.3,
    sugar: 6,
    sodium: 0.43,
    saturated_fat: 0.3,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Tortilla (flour)",
    brand: "Generic",
    barcode: null,
    calories: 304,
    protein: 8.3,
    carbs: 49.9,
    fat: 7.8,
    fiber: 3,
    sugar: 2.9,
    sodium: 0.616,
    saturated_fat: 1.9,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Couscous (cooked)",
    brand: "Generic",
    barcode: null,
    calories: 112,
    protein: 3.8,
    carbs: 23.2,
    fat: 0.2,
    fiber: 1.4,
    sugar: 0.1,
    sodium: 0.005,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "English Muffin",
    brand: "Generic",
    barcode: null,
    calories: 227,
    protein: 8.8,
    carbs: 44.2,
    fat: 1.7,
    fiber: 2.5,
    sugar: 2,
    sodium: 0.376,
    saturated_fat: 0.3,
    serving_size: "100g",
    source: "default"
  },

  // Condiments & Sauces
  {
    name: "Ketchup",
    brand: "Generic",
    barcode: null,
    calories: 112,
    protein: 1.1,
    carbs: 27.4,
    fat: 0.3,
    fiber: 0.3,
    sugar: 22.8,
    sodium: 1.11,
    saturated_fat: 0,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Mayonnaise",
    brand: "Generic",
    barcode: null,
    calories: 680,
    protein: 0.9,
    carbs: 0.6,
    fat: 75,
    fiber: 0,
    sugar: 0.6,
    sodium: 0.635,
    saturated_fat: 11.2,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "BBQ Sauce",
    brand: "Generic",
    barcode: null,
    calories: 172,
    protein: 0.8,
    carbs: 41,
    fat: 0.6,
    fiber: 0.3,
    sugar: 33,
    sodium: 1.05,
    saturated_fat: 0.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Ranch Dressing",
    brand: "Generic",
    barcode: null,
    calories: 430,
    protein: 1.4,
    carbs: 7.2,
    fat: 44.4,
    fiber: 0,
    sugar: 5.1,
    sodium: 0.933,
    saturated_fat: 7.1,
    serving_size: "100g",
    source: "default"
  },
  {
    name: "Soy Sauce",
    brand: "Generic",
    barcode: null,
    calories: 60,
    protein: 8,
    carbs: 5.6,
    fat: 0.1,
    fiber: 0.8,
    sugar: 0.4,
    sodium: 5.49,
    saturated_fat: 0,
    serving_size: "100ml",
    source: "default"
  },
  {
    name: "Hot Sauce",
    brand: "Generic",
    barcode: null,
    calories: 11,
    protein: 0.5,
    carbs: 2,
    fat: 0.3,
    fiber: 0.3,
    sugar: 1.3,
    sodium: 2.64,
    saturated_fat: 0,
    serving_size: "100ml",
    source: "default"
  }
];