/**
 * Sample Meal Library
 *
 * 50+ example meals for users to select as favorites
 * The AI will use these examples to learn the user's preferred meal styles
 */

export const SAMPLE_MEALS = {
  highProtein: [
    {
      id: 'grilled-chicken-rice-veggies',
      name: 'Grilled Chicken, Rice & Vegetables',
      description: 'Classic bodybuilding meal: grilled chicken breast, white rice, and steamed broccoli',
      calories: 600,
      protein: 50,
      carbs: 60,
      fat: 10,
      mealType: ['lunch', 'dinner'],
      cookTime: 25,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'salmon-quinoa-broccoli',
      name: 'Salmon, Quinoa & Broccoli',
      description: 'Baked salmon fillet with fluffy quinoa and roasted broccoli',
      calories: 550,
      protein: 45,
      carbs: 45,
      fat: 18,
      mealType: ['lunch', 'dinner'],
      cookTime: 30,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'lean-beef-sweet-potato-asparagus',
      name: 'Lean Beef, Sweet Potato & Asparagus',
      description: 'Grass-fed lean beef with roasted sweet potato and grilled asparagus',
      calories: 650,
      protein: 52,
      carbs: 55,
      fat: 16,
      mealType: ['dinner'],
      cookTime: 35,
      prepTime: 15,
      complexity: 'moderate',
    },
    {
      id: 'tuna-poke-bowl',
      name: 'Tuna Poke Bowl',
      description: 'Fresh tuna cubes over rice with edamame, cucumber, and avocado',
      calories: 580,
      protein: 48,
      carbs: 58,
      fat: 14,
      mealType: ['lunch', 'dinner'],
      cookTime: 15,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'chicken-stir-fry-brown-rice',
      name: 'Chicken Stir-Fry with Brown Rice',
      description: 'Lean chicken strips stir-fried with mixed vegetables over brown rice',
      calories: 620,
      protein: 48,
      carbs: 68,
      fat: 12,
      mealType: ['lunch', 'dinner'],
      cookTime: 20,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'turkey-meatballs-pasta',
      name: 'Turkey Meatballs with Pasta',
      description: 'Lean turkey meatballs with whole wheat pasta and marinara sauce',
      calories: 680,
      protein: 46,
      carbs: 75,
      fat: 16,
      mealType: ['lunch', 'dinner'],
      cookTime: 30,
      prepTime: 20,
      complexity: 'moderate',
    },
    {
      id: 'shrimp-fajita-bowl',
      name: 'Shrimp Fajita Bowl',
      description: 'Grilled shrimp with peppers, onions, rice, beans, and salsa',
      calories: 590,
      protein: 44,
      carbs: 62,
      fat: 14,
      mealType: ['lunch', 'dinner'],
      cookTime: 20,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'baked-cod-roasted-vegetables',
      name: 'Baked Cod with Roasted Vegetables',
      description: 'Herb-crusted cod fillet with colorful roasted vegetables',
      calories: 520,
      protein: 46,
      carbs: 42,
      fat: 12,
      mealType: ['lunch', 'dinner'],
      cookTime: 30,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'chicken-breast-mashed-potatoes',
      name: 'Chicken Breast with Mashed Potatoes',
      description: 'Pan-seared chicken breast with creamy mashed potatoes and green beans',
      calories: 640,
      protein: 50,
      carbs: 58,
      fat: 14,
      mealType: ['dinner'],
      cookTime: 30,
      prepTime: 15,
      complexity: 'moderate',
    },
    {
      id: 'grilled-steak-green-beans',
      name: 'Grilled Steak with Green Beans',
      description: 'Lean sirloin steak with garlic green beans and baked potato',
      calories: 700,
      protein: 54,
      carbs: 52,
      fat: 22,
      mealType: ['dinner'],
      cookTime: 25,
      prepTime: 10,
      complexity: 'simple',
    },
  ],

  quickBreakfast: [
    {
      id: 'greek-yogurt-berries-granola',
      name: 'Greek Yogurt, Berries & Granola',
      description: 'High-protein Greek yogurt topped with mixed berries and crunchy granola',
      calories: 350,
      protein: 25,
      carbs: 42,
      fat: 8,
      mealType: ['breakfast'],
      cookTime: 0,
      prepTime: 5,
      complexity: 'simple',
    },
    {
      id: 'protein-pancakes-fruit',
      name: 'Protein Pancakes with Fruit',
      description: 'Fluffy protein-packed pancakes topped with fresh fruit and maple syrup',
      calories: 400,
      protein: 30,
      carbs: 48,
      fat: 10,
      mealType: ['breakfast'],
      cookTime: 15,
      prepTime: 5,
      complexity: 'simple',
    },
    {
      id: 'egg-white-omelet-veggies',
      name: 'Egg White Omelet with Veggies',
      description: 'Fluffy egg white omelet loaded with spinach, tomatoes, and mushrooms',
      calories: 250,
      protein: 28,
      carbs: 18,
      fat: 6,
      mealType: ['breakfast'],
      cookTime: 10,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'overnight-oats-protein',
      name: 'Overnight Oats with Protein Powder',
      description: 'Creamy overnight oats mixed with protein powder, chia seeds, and banana',
      calories: 420,
      protein: 32,
      carbs: 52,
      fat: 10,
      mealType: ['breakfast'],
      cookTime: 0,
      prepTime: 5,
      complexity: 'simple',
    },
    {
      id: 'scrambled-eggs-toast-avocado',
      name: 'Scrambled Eggs with Toast & Avocado',
      description: 'Creamy scrambled eggs with whole grain toast and fresh avocado slices',
      calories: 450,
      protein: 24,
      carbs: 38,
      fat: 22,
      mealType: ['breakfast'],
      cookTime: 10,
      prepTime: 5,
      complexity: 'simple',
    },
    {
      id: 'smoothie-bowl',
      name: 'Smoothie Bowl',
      description: 'Thick smoothie bowl with protein powder, banana, berries, and toppings',
      calories: 380,
      protein: 28,
      carbs: 50,
      fat: 8,
      mealType: ['breakfast'],
      cookTime: 5,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'breakfast-burrito',
      name: 'Breakfast Burrito',
      description: 'Whole wheat tortilla filled with scrambled eggs, black beans, and cheese',
      calories: 480,
      protein: 26,
      carbs: 52,
      fat: 18,
      mealType: ['breakfast'],
      cookTime: 15,
      prepTime: 10,
      complexity: 'moderate',
    },
    {
      id: 'cottage-cheese-fruit-nuts',
      name: 'Cottage Cheese with Fruit & Nuts',
      description: 'Low-fat cottage cheese topped with pineapple, almonds, and honey',
      calories: 320,
      protein: 28,
      carbs: 35,
      fat: 8,
      mealType: ['breakfast', 'snack'],
      cookTime: 0,
      prepTime: 5,
      complexity: 'simple',
    },
    {
      id: 'protein-waffle-peanut-butter',
      name: 'Protein Waffle with Peanut Butter',
      description: 'Crispy protein waffle drizzled with natural peanut butter and berries',
      calories: 440,
      protein: 32,
      carbs: 42,
      fat: 16,
      mealType: ['breakfast'],
      cookTime: 10,
      prepTime: 5,
      complexity: 'simple',
    },
    {
      id: 'veggie-frittata',
      name: 'Veggie Frittata',
      description: 'Baked egg frittata loaded with vegetables and feta cheese',
      calories: 360,
      protein: 26,
      carbs: 22,
      fat: 18,
      mealType: ['breakfast'],
      cookTime: 25,
      prepTime: 15,
      complexity: 'moderate',
    },
  ],

  easyLunches: [
    {
      id: 'turkey-wrap-hummus',
      name: 'Turkey Wrap with Hummus',
      description: 'Whole wheat wrap with turkey, hummus, lettuce, tomato, and cucumber',
      calories: 450,
      protein: 35,
      carbs: 48,
      fat: 12,
      mealType: ['lunch'],
      cookTime: 0,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'chicken-caesar-salad',
      name: 'Chicken Caesar Salad',
      description: 'Grilled chicken breast over romaine lettuce with Caesar dressing and parmesan',
      calories: 500,
      protein: 40,
      carbs: 28,
      fat: 24,
      mealType: ['lunch'],
      cookTime: 10,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'quinoa-buddha-bowl',
      name: 'Quinoa Buddha Bowl',
      description: 'Quinoa bowl with chickpeas, roasted vegetables, tahini sauce, and greens',
      calories: 520,
      protein: 22,
      carbs: 68,
      fat: 18,
      mealType: ['lunch', 'dinner'],
      cookTime: 30,
      prepTime: 15,
      complexity: 'moderate',
    },
    {
      id: 'chicken-rice-bowl',
      name: 'Chicken & Rice Bowl',
      description: 'Seasoned chicken over jasmine rice with corn, beans, and salsa',
      calories: 580,
      protein: 42,
      carbs: 64,
      fat: 14,
      mealType: ['lunch', 'dinner'],
      cookTime: 20,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'tuna-salad-sandwich',
      name: 'Tuna Salad Sandwich',
      description: 'Light tuna salad on whole grain bread with lettuce and tomato',
      calories: 420,
      protein: 32,
      carbs: 45,
      fat: 12,
      mealType: ['lunch'],
      cookTime: 0,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'greek-salad-grilled-chicken',
      name: 'Greek Salad with Grilled Chicken',
      description: 'Traditional Greek salad topped with grilled chicken and olive oil dressing',
      calories: 480,
      protein: 38,
      carbs: 32,
      fat: 22,
      mealType: ['lunch'],
      cookTime: 15,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'veggie-hummus-wrap',
      name: 'Veggie & Hummus Wrap',
      description: 'Colorful vegetables with hummus wrapped in a whole wheat tortilla',
      calories: 380,
      protein: 16,
      carbs: 58,
      fat: 12,
      mealType: ['lunch'],
      cookTime: 0,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'chicken-quesadilla',
      name: 'Chicken Quesadilla',
      description: 'Grilled chicken and cheese quesadilla with salsa and Greek yogurt',
      calories: 540,
      protein: 38,
      carbs: 48,
      fat: 20,
      mealType: ['lunch', 'dinner'],
      cookTime: 10,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'asian-noodle-bowl',
      name: 'Asian Noodle Bowl',
      description: 'Rice noodles with chicken, vegetables, and savory Asian sauce',
      calories: 560,
      protein: 36,
      carbs: 72,
      fat: 14,
      mealType: ['lunch', 'dinner'],
      cookTime: 15,
      prepTime: 15,
      complexity: 'moderate',
    },
    {
      id: 'caprese-salad-chicken',
      name: 'Caprese Salad with Chicken',
      description: 'Fresh mozzarella, tomatoes, basil, and grilled chicken with balsamic glaze',
      calories: 460,
      protein: 40,
      carbs: 24,
      fat: 22,
      mealType: ['lunch'],
      cookTime: 10,
      prepTime: 10,
      complexity: 'simple',
    },
  ],

  vegetarianVegan: [
    {
      id: 'tofu-stir-fry',
      name: 'Tofu Stir-Fry',
      description: 'Crispy tofu cubes stir-fried with vegetables and teriyaki sauce over rice',
      calories: 520,
      protein: 28,
      carbs: 68,
      fat: 16,
      mealType: ['lunch', 'dinner'],
      cookTime: 20,
      prepTime: 15,
      complexity: 'moderate',
    },
    {
      id: 'lentil-curry-rice',
      name: 'Lentil Curry with Rice',
      description: 'Hearty red lentil curry with coconut milk served over basmati rice',
      calories: 580,
      protein: 24,
      carbs: 88,
      fat: 14,
      mealType: ['lunch', 'dinner'],
      cookTime: 35,
      prepTime: 10,
      complexity: 'moderate',
    },
    {
      id: 'black-bean-burrito-bowl',
      name: 'Black Bean Burrito Bowl',
      description: 'Black beans, rice, corn, salsa, guacamole, and vegetables',
      calories: 540,
      protein: 22,
      carbs: 82,
      fat: 16,
      mealType: ['lunch', 'dinner'],
      cookTime: 20,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'chickpea-salad',
      name: 'Chickpea Salad',
      description: 'Protein-rich chickpea salad with cucumber, tomatoes, and lemon dressing',
      calories: 420,
      protein: 18,
      carbs: 58,
      fat: 14,
      mealType: ['lunch'],
      cookTime: 0,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'veggie-pasta-primavera',
      name: 'Veggie Pasta Primavera',
      description: 'Whole wheat pasta tossed with seasonal vegetables and garlic olive oil',
      calories: 560,
      protein: 20,
      carbs: 88,
      fat: 16,
      mealType: ['lunch', 'dinner'],
      cookTime: 20,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'quinoa-stuffed-peppers',
      name: 'Quinoa Stuffed Peppers',
      description: 'Bell peppers stuffed with quinoa, beans, vegetables, and cheese',
      calories: 480,
      protein: 20,
      carbs: 68,
      fat: 14,
      mealType: ['dinner'],
      cookTime: 45,
      prepTime: 20,
      complexity: 'moderate',
    },
    {
      id: 'tempeh-buddha-bowl',
      name: 'Tempeh Buddha Bowl',
      description: 'Marinated tempeh with quinoa, roasted vegetables, and tahini sauce',
      calories: 540,
      protein: 26,
      carbs: 62,
      fat: 22,
      mealType: ['lunch', 'dinner'],
      cookTime: 30,
      prepTime: 15,
      complexity: 'moderate',
    },
    {
      id: 'vegetable-pad-thai',
      name: 'Vegetable Pad Thai',
      description: 'Rice noodles with tofu, vegetables, peanuts, and tangy pad thai sauce',
      calories: 600,
      protein: 22,
      carbs: 82,
      fat: 20,
      mealType: ['lunch', 'dinner'],
      cookTime: 20,
      prepTime: 20,
      complexity: 'moderate',
    },
  ],

  onePotQuick: [
    {
      id: 'one-pot-chicken-rice',
      name: 'One-Pot Chicken & Rice',
      description: 'Everything cooked together: chicken thighs, rice, vegetables, and spices',
      calories: 620,
      protein: 46,
      carbs: 68,
      fat: 14,
      mealType: ['dinner'],
      cookTime: 40,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'sheet-pan-salmon-vegetables',
      name: 'Sheet Pan Salmon & Vegetables',
      description: 'Salmon fillet and vegetables roasted together on a single sheet pan',
      calories: 540,
      protein: 44,
      carbs: 38,
      fat: 20,
      mealType: ['dinner'],
      cookTime: 25,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'slow-cooker-chili',
      name: 'Slow Cooker Chili',
      description: 'Set-and-forget beef and bean chili with tomatoes and spices',
      calories: 580,
      protein: 42,
      carbs: 58,
      fat: 18,
      mealType: ['dinner'],
      cookTime: 240,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'instant-pot-chicken-teriyaki',
      name: 'Instant Pot Chicken Teriyaki',
      description: 'Quick pressure-cooked chicken teriyaki with vegetables',
      calories: 560,
      protein: 48,
      carbs: 62,
      fat: 10,
      mealType: ['dinner'],
      cookTime: 20,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'skillet-pasta-chicken',
      name: 'Skillet Pasta with Chicken',
      description: 'One-pan pasta dish with chicken, tomatoes, and Italian seasonings',
      calories: 640,
      protein: 42,
      carbs: 78,
      fat: 16,
      mealType: ['dinner'],
      cookTime: 25,
      prepTime: 10,
      complexity: 'simple',
    },
    {
      id: 'stir-fry-any-protein',
      name: 'Quick Stir-Fry',
      description: 'Fast stir-fry with your choice of protein and mixed vegetables',
      calories: 580,
      protein: 40,
      carbs: 62,
      fat: 14,
      mealType: ['lunch', 'dinner'],
      cookTime: 15,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'chicken-noodle-soup',
      name: 'Chicken Noodle Soup',
      description: 'Comforting homemade chicken soup with noodles and vegetables',
      calories: 380,
      protein: 32,
      carbs: 48,
      fat: 8,
      mealType: ['lunch', 'dinner'],
      cookTime: 30,
      prepTime: 15,
      complexity: 'simple',
    },
    {
      id: 'fried-rice-vegetables',
      name: 'Fried Rice with Vegetables',
      description: 'Easy fried rice with eggs, mixed vegetables, and soy sauce',
      calories: 520,
      protein: 20,
      carbs: 78,
      fat: 14,
      mealType: ['lunch', 'dinner'],
      cookTime: 15,
      prepTime: 10,
      complexity: 'simple',
    },
  ],
};

/**
 * Get all meals as a flat array
 */
export function getAllMeals() {
  return [
    ...SAMPLE_MEALS.highProtein,
    ...SAMPLE_MEALS.quickBreakfast,
    ...SAMPLE_MEALS.easyLunches,
    ...SAMPLE_MEALS.vegetarianVegan,
    ...SAMPLE_MEALS.onePotQuick,
  ];
}

/**
 * Get meals by category
 */
export function getMealsByCategory(category) {
  return SAMPLE_MEALS[category] || [];
}

/**
 * Get meal by ID
 */
export function getMealById(id) {
  const allMeals = getAllMeals();
  return allMeals.find(meal => meal.id === id);
}

/**
 * Get meals by meal type (breakfast, lunch, dinner, snack)
 */
export function getMealsByType(mealType) {
  const allMeals = getAllMeals();
  return allMeals.filter(meal => meal.mealType.includes(mealType));
}

/**
 * Category metadata
 */
export const MEAL_CATEGORIES = {
  highProtein: {
    name: 'High-Protein Meals',
    icon: 'fitness',
    description: 'Protein-focused meals for muscle building (45-55g protein)',
  },
  quickBreakfast: {
    name: 'Quick Breakfasts',
    icon: 'sunny',
    description: 'Fast morning meals ready in 15 minutes or less',
  },
  easyLunches: {
    name: 'Easy Lunches',
    icon: 'restaurant',
    description: 'Simple midday meals perfect for meal prep',
  },
  vegetarianVegan: {
    name: 'Vegetarian/Vegan',
    icon: 'leaf',
    description: 'Plant-based protein options',
  },
  onePotQuick: {
    name: 'One-Pot & Quick',
    icon: 'time',
    description: 'Minimal cleanup, maximum convenience',
  },
};
